{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.dotfiles.security.enterprise;
in
{
  options.dotfiles.security.enterprise = {
    enable = mkEnableOption "Enterprise-grade security system";
    
    zeroTrust = mkOption {
      type = types.bool;
      default = true;
      description = "Enable Zero Trust Architecture components";
    };
    
    threatProtection = mkOption {
      type = types.bool;
      default = true;
      description = "Enable advanced threat protection and monitoring";
    };
    
    dataProtection = mkOption {
      type = types.bool;
      default = true;
      description = "Enable data protection and encryption";
    };
    
    complianceMonitoring = mkOption {
      type = types.bool;
      default = true;
      description = "Enable compliance monitoring and reporting";
    };
    
    auditLogging = mkOption {
      type = types.bool;
      default = true;
      description = "Enable comprehensive audit logging";
    };
    
    networkSecurity = mkOption {
      type = types.bool;
      default = true;
      description = "Enable network security monitoring";
    };
    
    incidentResponse = mkOption {
      type = types.bool;
      default = true;
      description = "Enable automated incident response";
    };
    
    securityLevel = mkOption {
      type = types.enum [ "standard" "high" "critical" ];
      default = "high";
      description = "Security enforcement level";
    };
    
    auditLogRetention = mkOption {
      type = types.int;
      default = 90;
      description = "Audit log retention period in days";
    };
  };

  config = mkIf cfg.enable {
    # Enterprise security packages (macOS compatible)
    home-manager.users.yuki.home.packages = with pkgs; [
      # Security monitoring tools
      nmap
      # wireshark - GUI application, skip for now
      # tcpdump - System binary on macOS
      
      # Encryption and crypto tools
      gnupg
      age
      sops
      
      # Network security
      openssh
      
      # Security scanning (macOS compatible)
      # clamav - Will be configured separately
      
    ] ++ optionals cfg.threatProtection [
      # Threat detection tools (cross-platform)
      # rkhunter - Linux specific, not available on macOS
      # chkrootkit - Linux specific, not available on macOS
      
    ] ++ optionals cfg.networkSecurity [
      # Network analysis
      netcat-gnu
      curl
      wget
      
    ] ++ optionals cfg.auditLogging [
      # Logging and monitoring (cross-platform)
      # rsyslog - Linux specific, macOS uses different logging
      # logrotate - Linux specific, macOS uses different log management
    ];

    # Zero Trust Architecture implementation
    home-manager.users.yuki.home.file.".config/security/zero-trust.conf" = mkIf cfg.zeroTrust {
      text = ''
        # Zero Trust Architecture Configuration
        # Generated by Enterprise Security Module
        
        # Identity and Access Management
        [identity]
        enforce_mfa=true
        session_timeout=3600
        max_failed_attempts=3
        account_lockout_duration=900
        
        # Network Security
        [network]
        default_deny=true
        micro_segmentation=enabled
        encrypted_communications=required
        vpn_required=true
        
        # Device Security
        [device]
        device_registration=required
        device_encryption=mandatory
        device_monitoring=enabled
        compliance_check=strict
        
        # Data Classification
        [data]
        classification_required=true
        encryption_at_rest=aes256
        encryption_in_transit=tls13
        data_loss_prevention=enabled
        
        # Audit and Compliance
        [audit]
        log_all_access=true
        real_time_monitoring=enabled
        compliance_reporting=automated
        retention_days=${toString cfg.auditLogRetention}
      '';
    };

    # Threat Protection System
    home-manager.users.yuki.home.file."bin/security-threat-monitor" = mkIf cfg.threatProtection {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Enterprise Threat Protection System
        set -euo pipefail
        
        ACTION="''${1:-monitor}"
        ALERT_LEVEL="''${2:-high}"
        
        echo "🛡️  Enterprise Threat Protection System"
        echo "======================================"
        echo "Action: $ACTION"
        echo "Alert Level: $ALERT_LEVEL"
        echo "Security Level: ${cfg.securityLevel}"
        echo ""
        
        # Security log directory
        SECURITY_LOG_DIR="$HOME/.security/logs"
        mkdir -p "$SECURITY_LOG_DIR"
        
        case "$ACTION" in
          "monitor")
            echo "🔍 Starting threat monitoring..."
            
            # Real-time system monitoring
            echo "$(date): Starting threat monitoring session" >> "$SECURITY_LOG_DIR/threat-monitor.log"
            
            # Check for suspicious processes
            echo "📊 Process Analysis:"
            
            # High CPU usage processes
            HIGH_CPU=$(ps aux | awk '$3 > 80.0 {print $2, $3, $11}' | head -5)
            if [[ -n "$HIGH_CPU" ]]; then
              echo "⚠️  High CPU processes detected:"
              echo "$HIGH_CPU"
              echo "$(date): High CPU processes: $HIGH_CPU" >> "$SECURITY_LOG_DIR/threat-monitor.log"
            else
              echo "✅ No suspicious CPU usage detected"
            fi
            
            # Network connections
            echo ""
            echo "🌐 Network Analysis:"
            
            # Check for unusual network connections
            if command -v netstat &> /dev/null; then
              EXTERNAL_CONNECTIONS=$(netstat -an | grep ESTABLISHED | grep -v "127.0.0.1\|::1" | wc -l | tr -d ' ')
              echo "📡 External connections: $EXTERNAL_CONNECTIONS"
              
              if [[ "$EXTERNAL_CONNECTIONS" -gt 20 ]]; then
                echo "⚠️  High number of external connections detected"
                echo "$(date): High external connections: $EXTERNAL_CONNECTIONS" >> "$SECURITY_LOG_DIR/threat-monitor.log"
              else
                echo "✅ Normal network activity"
              fi
            fi
            
            # File system monitoring
            echo ""
            echo "📁 File System Analysis:"
            
            # Check for recently modified sensitive files
            SENSITIVE_DIRS=("$HOME/.ssh" "$HOME/.gnupg" "/etc/passwd" "/etc/sudoers")
            
            for dir in "''${SENSITIVE_DIRS[@]}"; do
              if [[ -e "$dir" ]]; then
                RECENT_CHANGES=$(find "$dir" -mtime -1 2>/dev/null | wc -l | tr -d ' ')
                if [[ "$RECENT_CHANGES" -gt 0 ]]; then
                  echo "⚠️  Recent changes in sensitive directory: $dir"
                  echo "$(date): Sensitive file changes in $dir" >> "$SECURITY_LOG_DIR/threat-monitor.log"
                fi
              fi
            done
            
            # Security scan
            echo ""
            echo "🔐 Security Scan:"
            
            # Check SSH configuration
            if [[ -f "$HOME/.ssh/config" ]]; then
              if grep -q "PasswordAuthentication yes" "$HOME/.ssh/config" 2>/dev/null; then
                echo "⚠️  SSH password authentication enabled (security risk)"
                echo "$(date): SSH password auth enabled" >> "$SECURITY_LOG_DIR/threat-monitor.log"
              else
                echo "✅ SSH configuration secure"
              fi
            fi
            
            # Check for weak file permissions
            WEAK_PERMS=$(find "$HOME" -type f -perm -o+w 2>/dev/null | head -5)
            if [[ -n "$WEAK_PERMS" ]]; then
              echo "⚠️  World-writable files detected:"
              echo "$WEAK_PERMS"
              echo "$(date): World-writable files found" >> "$SECURITY_LOG_DIR/threat-monitor.log"
            else
              echo "✅ File permissions secure"
            fi
            ;;
            
          "scan")
            echo "🔎 Running comprehensive security scan..."
            
            # Rootkit detection
            if command -v chkrootkit &> /dev/null; then
              echo "🔍 Running rootkit scan..."
              if chkrootkit -q; then
                echo "✅ No rootkits detected"
              else
                echo "⚠️  Potential rootkit activity detected"
                echo "$(date): Rootkit scan flagged issues" >> "$SECURITY_LOG_DIR/threat-monitor.log"
              fi
            fi
            
            # Network port scan
            echo ""
            echo "🌐 Network port analysis..."
            if command -v nmap &> /dev/null; then
              echo "Scanning open ports..."
              OPEN_PORTS=$(nmap -sT localhost 2>/dev/null | grep "open" | wc -l | tr -d ' ')
              echo "📡 Open ports: $OPEN_PORTS"
              
              if [[ "$OPEN_PORTS" -gt 10 ]]; then
                echo "⚠️  High number of open ports detected"
                echo "$(date): High open ports: $OPEN_PORTS" >> "$SECURITY_LOG_DIR/threat-monitor.log"
              fi
            fi
            
            # System integrity check
            echo ""
            echo "🔐 System integrity verification..."
            
            # Check system binaries
            CRITICAL_BINARIES=("/bin/bash" "/usr/bin/sudo" "/usr/bin/ssh")
            for binary in "''${CRITICAL_BINARIES[@]}"; do
              if [[ -f "$binary" ]]; then
                # Simple existence check (more sophisticated checking would require signatures)
                echo "✅ Critical binary verified: $binary"
              else
                echo "❌ Critical binary missing: $binary"
                echo "$(date): Missing critical binary: $binary" >> "$SECURITY_LOG_DIR/threat-monitor.log"
              fi
            done
            ;;
            
          "incident")
            echo "🚨 Incident Response Protocol"
            
            INCIDENT_ID="INC-$(date +%Y%m%d-%H%M%S)"
            INCIDENT_LOG="$SECURITY_LOG_DIR/incident-$INCIDENT_ID.log"
            
            echo "📋 Incident ID: $INCIDENT_ID"
            echo "📁 Incident Log: $INCIDENT_LOG"
            echo ""
            
            # Incident logging
            {
              echo "=== SECURITY INCIDENT REPORT ==="
              echo "Incident ID: $INCIDENT_ID"
              echo "Timestamp: $(date)"
              echo "Alert Level: $ALERT_LEVEL"
              echo "System: $(uname -a)"
              echo "User: $(whoami)"
              echo ""
              
              echo "=== SYSTEM SNAPSHOT ==="
              echo "Running processes:"
              ps aux | head -20
              echo ""
              
              echo "Network connections:"
              netstat -an 2>/dev/null | head -20 || echo "netstat not available"
              echo ""
              
              echo "Recent system changes:"
              find /tmp -mtime -1 2>/dev/null | head -10 || echo "No recent changes in /tmp"
              echo ""
              
              echo "=== RECOMMENDED ACTIONS ==="
              case "$ALERT_LEVEL" in
                "critical")
                  echo "1. Isolate affected systems immediately"
                  echo "2. Preserve evidence for forensic analysis"
                  echo "3. Activate incident response team"
                  echo "4. Notify security operations center"
                  ;;
                "high")
                  echo "1. Investigate suspicious activity"
                  echo "2. Monitor system closely"
                  echo "3. Prepare for potential escalation"
                  echo "4. Document all findings"
                  ;;
                *)
                  echo "1. Log incident for review"
                  echo "2. Continue monitoring"
                  echo "3. Apply security patches if needed"
                  ;;
              esac
              
            } > "$INCIDENT_LOG"
            
            echo "✅ Incident report generated: $INCIDENT_LOG"
            
            # Automatic notification (if configured)
            if [[ -f "$HOME/.config/security/notification.conf" ]]; then
              echo "📧 Sending incident notification..."
              # Notification logic would go here
            fi
            ;;
            
          "compliance")
            echo "📋 Compliance Assessment"
            
            COMPLIANCE_REPORT="$SECURITY_LOG_DIR/compliance-$(date +%Y%m%d).log"
            
            {
              echo "=== ENTERPRISE SECURITY COMPLIANCE REPORT ==="
              echo "Generated: $(date)"
              echo "Security Level: ${cfg.securityLevel}"
              echo ""
              
              echo "=== ZERO TRUST COMPLIANCE ==="
              # Check Zero Trust configuration
              if [[ -f "$HOME/.config/security/zero-trust.conf" ]]; then
                echo "✅ Zero Trust configuration present"
              else
                echo "❌ Zero Trust configuration missing"
              fi
              
              echo ""
              echo "=== DATA PROTECTION COMPLIANCE ==="
              
              # Check encryption
              if command -v gpg &> /dev/null; then
                echo "✅ GPG encryption available"
              else
                echo "❌ GPG encryption not configured"
              fi
              
              if command -v sops &> /dev/null; then
                echo "✅ SOPS secret management available"
              else
                echo "❌ SOPS secret management not configured"
              fi
              
              echo ""
              echo "=== AUDIT LOGGING COMPLIANCE ==="
              
              # Check logging configuration
              if [[ -d "$SECURITY_LOG_DIR" ]]; then
                LOG_COUNT=$(ls -1 "$SECURITY_LOG_DIR" | wc -l | tr -d ' ')
                echo "✅ Security logging active ($LOG_COUNT log files)"
              else
                echo "❌ Security logging not configured"
              fi
              
              echo ""
              echo "=== NETWORK SECURITY COMPLIANCE ==="
              
              # Check firewall status (macOS specific)
              if [[ "$(uname)" == "Darwin" ]]; then
                if sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate | grep -q "enabled"; then
                  echo "✅ macOS firewall enabled"
                else
                  echo "⚠️  macOS firewall disabled"
                fi
              fi
              
              echo ""
              echo "=== COMPLIANCE SCORE ==="
              echo "Assessment complete - Review findings above"
              
            } > "$COMPLIANCE_REPORT"
            
            echo "✅ Compliance report generated: $COMPLIANCE_REPORT"
            cat "$COMPLIANCE_REPORT"
            ;;
            
          *)
            echo "Usage: security-threat-monitor <action> [alert_level]"
            echo ""
            echo "Actions:"
            echo "  monitor     - Real-time threat monitoring"
            echo "  scan        - Comprehensive security scan"
            echo "  incident    - Generate incident report"
            echo "  compliance  - Compliance assessment"
            echo ""
            echo "Alert Levels: low, medium, high, critical"
            ;;
        esac
      '';
    };

    # Data Protection and Encryption
    home-manager.users.yuki.home.file."bin/security-data-protection" = mkIf cfg.dataProtection {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Enterprise Data Protection System
        set -euo pipefail
        
        ACTION="''${1:-status}"
        TARGET="''${2:-.}"
        
        echo "🔐 Enterprise Data Protection System"
        echo "==================================="
        echo "Action: $ACTION"
        echo "Target: $TARGET"
        echo ""
        
        case "$ACTION" in
          "status")
            echo "📊 Data Protection Status:"
            echo ""
            
            # Encryption tools availability
            echo "🔧 Encryption Tools:"
            
            if command -v gpg &> /dev/null; then
              GPG_VERSION=$(gpg --version | head -1)
              echo "  ✅ GPG: $GPG_VERSION"
            else
              echo "  ❌ GPG: Not available"
            fi
            
            if command -v age &> /dev/null; then
              AGE_VERSION=$(age --version 2>&1 | head -1 || echo "Unknown version")
              echo "  ✅ Age: $AGE_VERSION"
            else
              echo "  ❌ Age: Not available"
            fi
            
            if command -v sops &> /dev/null; then
              SOPS_VERSION=$(sops --version 2>&1 | head -1 || echo "Unknown version")
              echo "  ✅ SOPS: $SOPS_VERSION"
            else
              echo "  ❌ SOPS: Not available"
            fi
            
            # File system encryption status
            echo ""
            echo "💾 Storage Encryption:"
            
            if [[ "$(uname)" == "Darwin" ]]; then
              # Check FileVault status on macOS
              FILEVAULT_STATUS=$(fdesetup status 2>/dev/null || echo "Unknown")
              echo "  🍎 FileVault: $FILEVAULT_STATUS"
            else
              echo "  🐧 Linux encryption check not implemented"
            fi
            
            # Secure directories
            echo ""
            echo "📁 Secure Directories:"
            
            SECURE_DIRS=("$HOME/.gnupg" "$HOME/.ssh" "$HOME/.config/sops")
            for dir in "''${SECURE_DIRS[@]}"; do
              if [[ -d "$dir" ]]; then
                PERMS=$(ls -ld "$dir" | cut -d' ' -f1)
                echo "  ✅ $dir ($PERMS)"
              else
                echo "  ⚪ $dir (not present)"
              fi
            done
            ;;
            
          "encrypt")
            echo "🔒 Encrypting data: $TARGET"
            
            if [[ ! -e "$TARGET" ]]; then
              echo "❌ Target does not exist: $TARGET"
              exit 1
            fi
            
            # Choose encryption method
            if command -v age &> /dev/null; then
              echo "Using Age encryption..."
              
              # Generate recipient key if needed
              AGE_KEY_FILE="$HOME/.config/age/key.txt"
              if [[ ! -f "$AGE_KEY_FILE" ]]; then
                echo "Generating Age key..."
                mkdir -p "$(dirname "$AGE_KEY_FILE")"
                age-keygen -o "$AGE_KEY_FILE"
                chmod 600 "$AGE_KEY_FILE"
              fi
              
              # Get public key
              PUBLIC_KEY=$(age-keygen -y "$AGE_KEY_FILE")
              
              # Encrypt file
              if [[ -f "$TARGET" ]]; then
                age -r "$PUBLIC_KEY" -o "''${TARGET}.age" "$TARGET"
                echo "✅ File encrypted: ''${TARGET}.age"
              elif [[ -d "$TARGET" ]]; then
                tar czf - "$TARGET" | age -r "$PUBLIC_KEY" -o "''${TARGET}.tar.gz.age"
                echo "✅ Directory encrypted: ''${TARGET}.tar.gz.age"
              fi
              
            elif command -v gpg &> /dev/null; then
              echo "Using GPG encryption..."
              
              if [[ -f "$TARGET" ]]; then
                gpg --symmetric --cipher-algo AES256 --output "''${TARGET}.gpg" "$TARGET"
                echo "✅ File encrypted: ''${TARGET}.gpg"
              elif [[ -d "$TARGET" ]]; then
                tar czf - "$TARGET" | gpg --symmetric --cipher-algo AES256 --output "''${TARGET}.tar.gz.gpg"
                echo "✅ Directory encrypted: ''${TARGET}.tar.gz.gpg"
              fi
              
            else
              echo "❌ No encryption tools available"
              exit 1
            fi
            ;;
            
          "decrypt")
            echo "🔓 Decrypting data: $TARGET"
            
            if [[ ! -f "$TARGET" ]]; then
              echo "❌ Target file does not exist: $TARGET"
              exit 1
            fi
            
            # Determine encryption type and decrypt
            if [[ "$TARGET" == *.age ]]; then
              echo "Decrypting Age file..."
              AGE_KEY_FILE="$HOME/.config/age/key.txt"
              
              if [[ ! -f "$AGE_KEY_FILE" ]]; then
                echo "❌ Age key file not found: $AGE_KEY_FILE"
                exit 1
              fi
              
              OUTPUT_FILE="''${TARGET%.age}"
              age -d -i "$AGE_KEY_FILE" -o "$OUTPUT_FILE" "$TARGET"
              echo "✅ File decrypted: $OUTPUT_FILE"
              
            elif [[ "$TARGET" == *.gpg ]]; then
              echo "Decrypting GPG file..."
              OUTPUT_FILE="''${TARGET%.gpg}"
              gpg --decrypt --output "$OUTPUT_FILE" "$TARGET"
              echo "✅ File decrypted: $OUTPUT_FILE"
              
            else
              echo "❌ Unknown encryption format: $TARGET"
              exit 1
            fi
            ;;
            
          "secure-wipe")
            echo "🗑️  Securely wiping: $TARGET"
            
            if [[ ! -e "$TARGET" ]]; then
              echo "❌ Target does not exist: $TARGET"
              exit 1
            fi
            
            # Secure deletion
            if [[ "$(uname)" == "Darwin" ]]; then
              # macOS secure delete
              rm -P "$TARGET"
              echo "✅ Securely wiped (macOS): $TARGET"
            else
              # Linux secure delete
              if command -v shred &> /dev/null; then
                shred -vfz -n 3 "$TARGET"
                echo "✅ Securely wiped (shred): $TARGET"
              else
                # Fallback: overwrite with random data
                dd if=/dev/urandom of="$TARGET" bs=1M count=1 2>/dev/null
                rm "$TARGET"
                echo "✅ Securely wiped (dd): $TARGET"
              fi
            fi
            ;;
            
          "audit")
            echo "📋 Data Protection Audit"
            
            AUDIT_REPORT="$HOME/.security/logs/data-protection-audit-$(date +%Y%m%d).log"
            mkdir -p "$(dirname "$AUDIT_REPORT")"
            
            {
              echo "=== DATA PROTECTION AUDIT REPORT ==="
              echo "Generated: $(date)"
              echo "Target: $TARGET"
              echo ""
              
              echo "=== ENCRYPTION STATUS ==="
              
              # Find encrypted files
              ENCRYPTED_FILES=$(find "$TARGET" -type f \\( -name "*.gpg" -o -name "*.age" -o -name "*.enc" \\) 2>/dev/null | wc -l | tr -d ' ')
              echo "Encrypted files found: $ENCRYPTED_FILES"
              
              # Find potentially sensitive files
              SENSITIVE_PATTERNS=("*.key" "*.pem" "*.p12" "*.pfx" "*password*" "*secret*")
              SENSITIVE_COUNT=0
              
              for pattern in "''${SENSITIVE_PATTERNS[@]}"; do
                COUNT=$(find "$TARGET" -type f -name "$pattern" 2>/dev/null | wc -l | tr -d ' ')
                SENSITIVE_COUNT=$((SENSITIVE_COUNT + COUNT))
              done
              
              echo "Potentially sensitive files: $SENSITIVE_COUNT"
              
              echo ""
              echo "=== FILE PERMISSIONS AUDIT ==="
              
              # Check for world-readable sensitive files
              WORLD_READABLE=$(find "$TARGET" -type f -perm -o+r \\( -name "*key*" -o -name "*password*" -o -name "*secret*" \\) 2>/dev/null | wc -l | tr -d ' ')
              echo "World-readable sensitive files: $WORLD_READABLE"
              
              if [[ "$WORLD_READABLE" -gt 0 ]]; then
                echo "⚠️  World-readable sensitive files detected!"
                find "$TARGET" -type f -perm -o+r \\( -name "*key*" -o -name "*password*" -o -name "*secret*" \\) 2>/dev/null | head -5
              fi
              
              echo ""
              echo "=== RECOMMENDATIONS ==="
              
              if [[ "$SENSITIVE_COUNT" -gt 0 && "$ENCRYPTED_FILES" -eq 0 ]]; then
                echo "🔐 Consider encrypting sensitive files"
              fi
              
              if [[ "$WORLD_READABLE" -gt 0 ]]; then
                echo "🔒 Fix file permissions for sensitive files"
              fi
              
              echo ""
              echo "=== AUDIT COMPLETE ==="
              
            } > "$AUDIT_REPORT"
            
            echo "✅ Audit report generated: $AUDIT_REPORT"
            cat "$AUDIT_REPORT"
            ;;
            
          *)
            echo "Usage: security-data-protection <action> [target]"
            echo ""
            echo "Actions:"
            echo "  status       - Show data protection status"
            echo "  encrypt      - Encrypt file or directory"
            echo "  decrypt      - Decrypt file"
            echo "  secure-wipe  - Securely delete file"
            echo "  audit        - Audit data protection"
            echo ""
            echo "Target: File or directory path (default: current directory)"
            ;;
        esac
      '';
    };

    # Network Security Monitoring
    home-manager.users.yuki.home.file."bin/security-network-monitor" = mkIf cfg.networkSecurity {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Enterprise Network Security Monitor
        set -euo pipefail
        
        ACTION="''${1:-status}"
        
        echo "🌐 Enterprise Network Security Monitor"
        echo "====================================="
        echo "Action: $ACTION"
        echo ""
        
        case "$ACTION" in
          "status")
            echo "📊 Network Security Status:"
            echo ""
            
            # Firewall status
            echo "🛡️  Firewall Status:"
            if [[ "$(uname)" == "Darwin" ]]; then
              FIREWALL_STATUS=$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate 2>/dev/null || echo "Unable to check")
              echo "  macOS Firewall: $FIREWALL_STATUS"
            fi
            
            # Network interfaces
            echo ""
            echo "🔌 Network Interfaces:"
            if command -v ifconfig &> /dev/null; then
              ifconfig | grep -E "^[a-z]|inet " | head -10
            fi
            
            # Active connections
            echo ""
            echo "🔗 Active Connections:"
            if command -v netstat &> /dev/null; then
              CONNECTIONS=$(netstat -an | grep ESTABLISHED | wc -l | tr -d ' ')
              echo "  Established connections: $CONNECTIONS"
              
              # Show top connections
              echo "  Top external connections:"
              netstat -an | grep ESTABLISHED | grep -v "127.0.0.1\|::1" | head -5
            fi
            
            # DNS configuration
            echo ""
            echo "🔍 DNS Configuration:"
            if [[ -f "/etc/resolv.conf" ]]; then
              echo "  DNS servers:"
              grep nameserver /etc/resolv.conf | head -3
            fi
            ;;
            
          "scan")
            echo "🔎 Network Security Scan"
            
            # Port scan localhost
            echo ""
            echo "📡 Local Port Scan:"
            if command -v nmap &> /dev/null; then
              echo "Scanning localhost ports..."
              nmap -sT localhost | grep -E "open|filtered"
            else
              echo "nmap not available, using netstat..."
              netstat -an | grep LISTEN | head -10
            fi
            
            # Network route analysis
            echo ""
            echo "🛣️  Network Routes:"
            if command -v route &> /dev/null; then
              route -n | head -5
            elif command -v ip &> /dev/null; then
              ip route | head -5
            fi
            
            # ARP table
            echo ""
            echo "🏠 ARP Table:"
            if command -v arp &> /dev/null; then
              arp -a | head -5
            fi
            ;;
            
          "monitor")
            echo "👁️  Real-time Network Monitoring"
            
            MONITOR_LOG="$HOME/.security/logs/network-monitor-$(date +%Y%m%d-%H%M%S).log"
            mkdir -p "$(dirname "$MONITOR_LOG")"
            
            echo "📁 Logging to: $MONITOR_LOG"
            echo ""
            
            # Start monitoring
            {
              echo "=== NETWORK MONITORING SESSION ==="
              echo "Started: $(date)"
              echo ""
              
              for i in {1..60}; do
                echo "--- Interval $i ($(date)) ---"
                
                # Connection count
                if command -v netstat &> /dev/null; then
                  CONN_COUNT=$(netstat -an | grep ESTABLISHED | wc -l | tr -d ' ')
                  echo "Connections: $CONN_COUNT"
                fi
                
                # Network activity
                if [[ "$(uname)" == "Darwin" ]]; then
                  # macOS network statistics
                  BYTES_IN=$(netstat -ibn | awk 'FNR==2{print $7}')
                  BYTES_OUT=$(netstat -ibn | awk 'FNR==2{print $10}')
                  echo "Traffic: IN=$BYTES_IN OUT=$BYTES_OUT"
                fi
                
                sleep 5
              done
              
              echo ""
              echo "=== MONITORING SESSION COMPLETE ==="
              echo "Ended: $(date)"
              
            } > "$MONITOR_LOG"
            
            echo "✅ Network monitoring complete: $MONITOR_LOG"
            ;;
            
          *)
            echo "Usage: security-network-monitor <action>"
            echo ""
            echo "Actions:"
            echo "  status   - Show network security status"
            echo "  scan     - Network security scan"
            echo "  monitor  - Real-time network monitoring"
            ;;
        esac
      '';
    };

    # Security Health Check
    home-manager.users.yuki.home.file."bin/security-health" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail
        
        echo "🛡️  Enterprise Security Health Check"
        echo "===================================="
        echo ""
        
        ISSUES=0
        
        # Zero Trust Architecture
        ${if cfg.zeroTrust then ''
          echo "🏛️  Zero Trust Architecture:"
          if [[ -f "$HOME/.config/security/zero-trust.conf" ]]; then
            echo "  ✅ Zero Trust configuration: Available"
          else
            echo "  ❌ Zero Trust configuration: Not found"
            ((ISSUES++))
          fi
        '' else ''
          echo "🏛️  Zero Trust Architecture: Disabled"
        ''}
        
        # Threat Protection
        ${if cfg.threatProtection then ''
          echo ""
          echo "🛡️  Threat Protection:"
          if command -v security-threat-monitor &> /dev/null; then
            echo "  ✅ Threat monitoring: Available"
          else
            echo "  ❌ Threat monitoring: Not found"
            ((ISSUES++))
          fi
        '' else ''
          echo ""
          echo "🛡️  Threat Protection: Disabled"
        ''}
        
        # Data Protection
        ${if cfg.dataProtection then ''
          echo ""
          echo "🔐 Data Protection:"
          if command -v security-data-protection &> /dev/null; then
            echo "  ✅ Data protection: Available"
          else
            echo "  ❌ Data protection: Not found"
            ((ISSUES++))
          fi
          
          # Check encryption tools
          if command -v gpg &> /dev/null; then
            echo "  ✅ GPG encryption: Available"
          else
            echo "  ⚠️  GPG encryption: Not available"
          fi
          
          if command -v age &> /dev/null; then
            echo "  ✅ Age encryption: Available"
          else
            echo "  ⚠️  Age encryption: Not available"
          fi
          
          if command -v sops &> /dev/null; then
            echo "  ✅ SOPS secrets: Available"
          else
            echo "  ⚠️  SOPS secrets: Not available"
          fi
        '' else ''
          echo ""
          echo "🔐 Data Protection: Disabled"
        ''}
        
        # Network Security
        ${if cfg.networkSecurity then ''
          echo ""
          echo "🌐 Network Security:"
          if command -v security-network-monitor &> /dev/null; then
            echo "  ✅ Network monitoring: Available"
          else
            echo "  ❌ Network monitoring: Not found"
            ((ISSUES++))
          fi
          
          # Check firewall
          if [[ "$(uname)" == "Darwin" ]]; then
            if sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate | grep -q "enabled"; then
              echo "  ✅ macOS Firewall: Enabled"
            else
              echo "  ⚠️  macOS Firewall: Disabled"
            fi
          fi
        '' else ''
          echo ""
          echo "🌐 Network Security: Disabled"
        ''}
        
        # Audit Logging
        ${if cfg.auditLogging then ''
          echo ""
          echo "📋 Audit Logging:"
          if [[ -d "$HOME/.security/logs" ]]; then
            LOG_COUNT=$(ls -1 "$HOME/.security/logs" 2>/dev/null | wc -l | tr -d ' ')
            echo "  ✅ Security logs: $LOG_COUNT files"
          else
            echo "  ⚠️  Security logs: Directory not found"
          fi
        '' else ''
          echo ""
          echo "📋 Audit Logging: Disabled"
        ''}
        
        # System Security
        echo ""
        echo "💻 System Security:"
        
        # File permissions
        SECURE_DIRS=("$HOME/.ssh" "$HOME/.gnupg")
        for dir in "''${SECURE_DIRS[@]}"; do
          if [[ -d "$dir" ]]; then
            PERMS=$(ls -ld "$dir" | cut -d' ' -f1)
            if [[ "$PERMS" =~ ^d...---.-- ]]; then
              echo "  ✅ $dir: Secure permissions ($PERMS)"
            else
              echo "  ⚠️  $dir: Insecure permissions ($PERMS)"
            fi
          else
            echo "  ⚪ $dir: Not present"
          fi
        done
        
        # Summary
        echo ""
        echo "📊 Security Status:"
        echo "  🛡️  Security Level: ${cfg.securityLevel}"
        echo "  📅 Audit Retention: ${toString cfg.auditLogRetention} days"
        
        if [[ $ISSUES -eq 0 ]]; then
          echo "  ✅ Enterprise Security: Fully operational"
        else
          echo "  ⚠️  Enterprise Security: $ISSUES issues detected"
        fi
        
        echo ""
        echo "🚀 Available Commands:"
        echo "  security-threat-monitor   - Threat protection system"
        echo "  security-data-protection  - Data encryption and protection"
        echo "  security-network-monitor  - Network security monitoring"
        echo "  security-health          - This health check"
      '';
    };

    # Security aliases
    home-manager.users.yuki.home.file.".config/security/aliases.sh" = {
      text = ''
        # Enterprise Security Aliases
        alias sec-health="security-health"
        alias sec-threat="security-threat-monitor"
        alias sec-data="security-data-protection"
        alias sec-network="security-network-monitor"
        
        # Quick security commands
        alias sec-scan="security-threat-monitor scan"
        alias sec-monitor="security-threat-monitor monitor"
        alias sec-incident="security-threat-monitor incident"
        alias sec-compliance="security-threat-monitor compliance"
        
        # Data protection shortcuts
        alias encrypt="security-data-protection encrypt"
        alias decrypt="security-data-protection decrypt"
        alias secure-rm="security-data-protection secure-wipe"
        
        # Network security shortcuts
        alias net-scan="security-network-monitor scan"
        alias net-status="security-network-monitor status"
      '';
    };

    # Security environment variables
    home-manager.users.yuki.home.file.".config/security/environment.sh" = {
      text = ''
        # Enterprise Security Environment
        export SECURITY_SYSTEM_ENABLED="true"
        export SECURITY_LEVEL="${cfg.securityLevel}"
        export SECURITY_AUDIT_RETENTION="${toString cfg.auditLogRetention}"
        
        # Zero Trust settings
        ${if cfg.zeroTrust then ''
          export ZERO_TRUST_ENABLED="true"
        '' else ''
          export ZERO_TRUST_ENABLED="false"
        ''}
        
        # Security directories
        export SECURITY_LOG_DIR="$HOME/.security/logs"
        export SECURITY_CONFIG_DIR="$HOME/.config/security"
        
        # Create security directories
        mkdir -p "$SECURITY_LOG_DIR"
        mkdir -p "$SECURITY_CONFIG_DIR"
      '';
    };
  };
}