# Generated by compose2nix from /opt/stacks/anisette/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/anisette, /mnt/jellyfin-media became
# /srv, and the docker socket became podman's. Not regenerated by anything — the
# compose file it came from dies with Proxmox, so this is the source of truth now.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."anisette" = {
    image = "mirror.gcr.io/dadoum/anisette-v3-server:latest";
    volumes = [
      "/var/lib/homelab/anisette/lib:/home/Alcoholic/.config/anisette-v3/lib:rw"
    ];
    ports = [
      "6969:6969/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=anisette"
      "--network=anisette_default"
    ];
  };
  systemd.services."podman-anisette" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-anisette_default.service"
    ];
    requires = [
      "podman-network-anisette_default.service"
    ];
    partOf = [
      "podman-compose-anisette-root.target"
    ];
    wantedBy = [
      "podman-compose-anisette-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-anisette_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f anisette_default";
    };
    script = ''
      podman network inspect anisette_default || podman network create anisette_default
    '';
    partOf = [ "podman-compose-anisette-root.target" ];
    wantedBy = [ "podman-compose-anisette-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-anisette-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
