# Generated by compose2nix from /opt/stacks/archivebox/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/archivebox, /mnt/jellyfin-media became
# /srv, and every value that was interpolated from the stack's .env was dropped so
# that environmentFiles supplies it at runtime — see README.md for the keys each
# file must define. Nothing regenerates this; the compose file dies with Proxmox.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."archivebox" = {
    image = "archivebox/archivebox:latest";
    environmentFiles = [ "/var/lib/secrets/archivebox.env" ];
    environment = {
      "ADMIN_USERNAME" = "admin";
      "ALLOWED_HOSTS" = "*";
      "CSRF_TRUSTED_ORIGINS" = "https://archive.gapul.net";
      "PGID" = "1000";
      "PUBLIC_ADD_VIEW" = "False";
      "PUBLIC_INDEX" = "False";
      "PUBLIC_SNAPSHOTS" = "False";
      "PUID" = "1000";
      "SAVE_ARCHIVE_DOT_ORG" = "False";
      "SEARCH_BACKEND_ENGINE" = "ripgrep";
      "TZ" = "Asia/Tokyo";
    };
    volumes = [
      "/srv/archivebox:/data:rw"
    ];
    ports = [
      "8000:8000/tcp"
    ];
    cmd = [
      "server"
      "--quick-init"
      "0.0.0.0:8000"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=archivebox"
      "--network=archivebox_default"
    ];
  };
  systemd.services."podman-archivebox" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-archivebox_default.service"
    ];
    requires = [
      "podman-network-archivebox_default.service"
    ];
    partOf = [
      "podman-compose-archivebox-root.target"
    ];
    wantedBy = [
      "podman-compose-archivebox-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-archivebox_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f archivebox_default";
    };
    script = ''
      podman network inspect archivebox_default || podman network create archivebox_default
    '';
    partOf = [ "podman-compose-archivebox-root.target" ];
    wantedBy = [ "podman-compose-archivebox-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-archivebox-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
