# attic は nixpkgs のモジュールで直接動かす。postgres だけ compose2nix 由来の
# コンテナのまま。元は /opt/stacks/attic/compose.yaml。
#
# サーバ側をモジュールにした理由は、server.toml が /var/lib/homelab/attic に手で
# 置かれたまま宣言の外にあったことと、イメージが :latest だったこと。設定はここに来た。
#
# postgres を据え置いたのは、コンテナの postgres:16-alpine が musl でクラスタを作って
# いるため。glibc の postgres で同じ PGDATA を開くと照合順序が変わり、テキスト索引が
# 壊れうる。移すなら pg_dump 経由になるので、それは別の日にやる。
{
  pkgs,
  lib,
  config,
  ...
}:

let
  # モジュールは settings に既定の `database.url = "sqlite://…"` を入れてくる。attic は
  # 設定ファイルの値を環境変数より優先するので、ATTIC_SERVER_DATABASE_URL を渡しても
  # 効かず、空の SQLite を作ってそちらを見にいく (実際にそうなった)。sqlite は元の
  # 構成が CI の並列 push で接続プールを詰まらせて捨てた経緯があるので戻せない。
  #
  # かといって URL は接続情報そのもので、ストアは誰でも読める。宣言はそのままに、
  # URL だけ起動時に環境変数から差し込む。vpn-relay.nix と同じ手。
  serverToml = (pkgs.formats.toml { }).generate "atticd-server.toml" (
    lib.recursiveUpdate config.services.atticd.settings { database.url = "@DB_URL@"; }
  );
  mkServerToml = pkgs.writeShellScript "atticd-server-toml" ''
    set -eu
    ${pkgs.gnused}/bin/sed "s#@DB_URL@#$ATTIC_SERVER_DATABASE_URL#" \
      ${serverToml} > /run/atticd/server.toml
    chmod 600 /run/atticd/server.toml
  '';
in
{
  services.atticd = {
    enable = true;
    # ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64 と、postgres の URL
    # (ATTIC_SERVER_DATABASE_URL) がここに入っている。URL は接続情報そのものなので
    # settings には書かない。モジュールの設定検査はダミーの URL を渡して走るので、
    # database.url が無くても通る。
    environmentFile = "/var/lib/secrets/attic.env";
    settings = {
      # Caddy が cache.gapul.net をここへ流す。コンテナが 8083:8080 で publish して
      # いた側の番号に合わせてあるので、リバースプロキシ側は変えなくていい。
      listen = "127.0.0.1:8083";
      storage = {
        type = "local";
        # 2.3GB ある。/srv は自動スナップショットを切ってあるデータセットで、
        # キャッシュを世代ごとに抱え込まないのが狙い。
        path = "/srv/attic/storage";
      };
      chunking = {
        nar-size-threshold = 65536;
        min-size = 16384;
        avg-size = 65536;
        max-size = 262144;
      };
      compression.type = "zstd";
      garbage-collection.interval = "12 hours";
    };
  };

  # モジュールの既定は DynamicUser で、UID が再起動をまたいで変わりうる。ストレージは
  # /srv に既にあって所有者が固定なので、素の system user にする。
  users.users.atticd = {
    isSystemUser = true;
    group = "atticd";
  };
  users.groups.atticd = { };
  systemd.services.atticd = {
    after = [ "podman-attic-db.service" ];
    wants = [ "podman-attic-db.service" ];
    serviceConfig = {
      DynamicUser = lib.mkForce false;
      RuntimeDirectory = "atticd";
      RuntimeDirectoryMode = "0700";
      ExecStartPre = [ "${mkServerToml}" ];
      ExecStart = lib.mkForce "${lib.getExe config.services.atticd.package} -f /run/atticd/server.toml --mode ${config.services.atticd.mode}";
    };
  };

  # Containers
  virtualisation.oci-containers.containers."attic-db" = {
    image = "postgres:16-alpine";
    environmentFiles = [ "/var/lib/secrets/attic.env" ];
    environment = {
      "POSTGRES_DB" = "attic";
      "POSTGRES_USER" = "attic";
    };
    volumes = [
      "/srv/attic/pgdata:/var/lib/postgresql/data:rw"
    ];
    # atticd がホスト側から繋ぐ。compose の頃はコンテナ同士だったので publish は
    # 無かった。ループバックだけに出す。
    ports = [
      "127.0.0.1:5432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U attic -d attic"
      "--health-interval=10s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=attic_default"
    ];
  };
  systemd.services."podman-attic-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-attic_default.service"
    ];
    requires = [
      "podman-network-attic_default.service"
    ];
    partOf = [
      "podman-compose-attic-root.target"
    ];
    wantedBy = [
      "podman-compose-attic-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-attic_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f attic_default";
    };
    script = ''
      podman network inspect attic_default || podman network create attic_default
    '';
    partOf = [ "podman-compose-attic-root.target" ];
    wantedBy = [ "podman-compose-attic-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-attic-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
