# Generated by compose2nix from /opt/stacks/attic/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/attic, /mnt/jellyfin-media became
# /srv, and every value that was interpolated from the stack's .env was dropped so
# that environmentFiles supplies it at runtime — see README.md for the keys each
# file must define. Nothing regenerates this; the compose file dies with Proxmox.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."attic" = {
    image = "ghcr.io/zhaofengli/attic:latest";
    environmentFiles = [ "/var/lib/secrets/attic.env" ];
    volumes = [
      "/var/lib/homelab/attic/server.toml:/config/server.toml:ro"
      "/srv/attic:/data:rw"
    ];
    ports = [
      "8083:8080/tcp"
    ];
    cmd = [
      "-f"
      "/config/server.toml"
    ];
    dependsOn = [
      "attic-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=atticd"
      "--network=attic_default"
    ];
  };
  systemd.services."podman-attic" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-attic_default.service"
    ];
    requires = [
      "podman-network-attic_default.service"
    ];
    partOf = [
      "podman-compose-attic-root.target"
    ];
    wantedBy = [
      "podman-compose-attic-root.target"
    ];
  };
  virtualisation.oci-containers.containers."attic-db" = {
    image = "postgres:16-alpine";
    environmentFiles = [ "/var/lib/secrets/attic.env" ];
    environment = {
      "POSTGRES_DB" = "attic";
      "POSTGRES_USER" = "attic";
    };
    volumes = [
      "/srv/attic/pgdata:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U attic -d attic"
      "--health-interval=10s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=attic_default"
    ];
  };
  systemd.services."podman-attic-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-attic_default.service"
    ];
    requires = [
      "podman-network-attic_default.service"
    ];
    partOf = [
      "podman-compose-attic-root.target"
    ];
    wantedBy = [
      "podman-compose-attic-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-attic_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f attic_default";
    };
    script = ''
      podman network inspect attic_default || podman network create attic_default
    '';
    partOf = [ "podman-compose-attic-root.target" ];
    wantedBy = [ "podman-compose-attic-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-attic-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
