# Generated by compose2nix from /opt/stacks/forgejo/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/forgejo, /mnt/jellyfin-media became
# /srv, and the docker socket became podman's. Not regenerated by anything — the
# compose file it came from dies with Proxmox, so this is the source of truth now.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."forgejo" = {
    image = "codeberg.org/forgejo/forgejo:11";
    environment = {
      "FORGEJO__migrations__ALLOW_LOCALNETWORKS" = "false";
      "FORGEJO__security__INSTALL_LOCK" = "true";
      "FORGEJO__server__DISABLE_SSH" = "true";
      "FORGEJO__server__DOMAIN" = "git.gapul.net";
      "FORGEJO__server__ROOT_URL" = "https://git.gapul.net/";
      "FORGEJO__service__DISABLE_REGISTRATION" = "true";
      "USER_GID" = "1000";
      "USER_UID" = "1000";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/var/lib/homelab/forgejo/data:/data:rw"
    ];
    ports = [
      "3003:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"wget\", \"-qO-\", \"http://localhost:3000/api/healthz\"]"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-timeout=10s"
      "--network-alias=forgejo"
      "--network=forgejo_default"
    ];
  };
  systemd.services."podman-forgejo" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-forgejo_default.service"
    ];
    requires = [
      "podman-network-forgejo_default.service"
    ];
    partOf = [
      "podman-compose-forgejo-root.target"
    ];
    wantedBy = [
      "podman-compose-forgejo-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-forgejo_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f forgejo_default";
    };
    script = ''
      podman network inspect forgejo_default || podman network create forgejo_default
    '';
    partOf = [ "podman-compose-forgejo-root.target" ];
    wantedBy = [ "podman-compose-forgejo-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-forgejo-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
