# Generated by compose2nix from /opt/stacks/homepage/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/homepage, /mnt/jellyfin-media became
# /srv, and the docker socket became podman's. Not regenerated by anything — the
# compose file it came from dies with Proxmox, so this is the source of truth now.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # /app/config は書ける必要がある。homepage は起動時に logs/ を作り、置いていない
  # 設定 (kubernetes.yaml など) は雛形を自分でコピーしてくるので、store を直接 ro で
  # 当てると初期化に失敗して 500 を返す。宣言はリポジトリ側のままにして、起動ごとに
  # 書ける場所へ配り直す。手で編集しても次の起動で戻る、が狙いどおりの挙動。
  #
  # yaml だけ消してから配るので、homepage が作った雛形も毎回作り直される。logs/ は
  # ディレクトリなので残る。
  systemd.services."podman-homepage".preStart = lib.mkAfter ''
    install -d -m 755 /var/lib/homelab/homepage
    find /var/lib/homelab/homepage -maxdepth 1 -type f -name "*.yaml" -delete
    cp -L ${../../configs/homelab/homepage}/*.yaml /var/lib/homelab/homepage/
    chmod u+w /var/lib/homelab/homepage/*.yaml
  '';

  # Containers
  virtualisation.oci-containers.containers."glances" = {
    image = "docker.io/nicolargo/glances:latest-full";
    environment = {
      "GLANCES_OPT" = "-w";
    };
    volumes = [
      "/etc/os-release:/etc/os-release:ro"
      # podman's socket speaks the Docker API, but homepage's config/docker.yaml and
      # glances both look for it at the conventional path, so keep the container
      # side unchanged and only swap the host side.
      "/run/podman/podman.sock:/var/run/docker.sock:ro"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-glances" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-homepage-root.target"
    ];
    wantedBy = [
      "podman-compose-homepage-root.target"
    ];
  };
  virtualisation.oci-containers.containers."homepage" = {
    image = "ghcr.io/gethomepage/homepage:latest";
    environment = {
      "HOMEPAGE_ALLOWED_HOSTS" = "*";
    };
    volumes = [
      # 中身は preStart がリポジトリ(configs/homelab/homepage)から配る。以前は
      # /var/lib 側の手編集ファイルで、移行のたびに旧ホストの IP を直す作業が出ていた。
      "/var/lib/homelab/homepage:/app/config:rw"
      # podman's socket speaks the Docker API, but homepage's config/docker.yaml and
      # glances both look for it at the conventional path, so keep the container
      # side unchanged and only swap the host side.
      "/run/podman/podman.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=homepage"
      "--network=homepage_default"
    ];
  };
  systemd.services."podman-homepage" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-homepage_default.service"
    ];
    requires = [
      "podman-network-homepage_default.service"
    ];
    partOf = [
      "podman-compose-homepage-root.target"
    ];
    wantedBy = [
      "podman-compose-homepage-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-homepage_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f homepage_default";
    };
    script = ''
      podman network inspect homepage_default || podman network create homepage_default
    '';
    partOf = [ "podman-compose-homepage-root.target" ];
    wantedBy = [ "podman-compose-homepage-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-homepage-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
