# Generated by compose2nix from /opt/stacks/homepage/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/homepage, /mnt/jellyfin-media became
# /srv, and the docker socket became podman's. Not regenerated by anything — the
# compose file it came from dies with Proxmox, so this is the source of truth now.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # /app/config has to be writable: homepage creates logs/ at startup and copies in
  # templates for any config it does not find (kubernetes.yaml etc.), so a read-only
  # store path fails initialisation with a 500. The declaration stays in the repo and
  # is re-copied into a writable place on every start. Hand edits are reverted on the
  # next start, which is the intended behaviour.
  #
  # Only the yaml files are deleted before copying, so homepage's own templates are
  # regenerated each time too. logs/ is a directory and survives.
  systemd.services."podman-homepage".preStart = lib.mkAfter ''
    install -d -m 755 /var/lib/homelab/homepage
    find /var/lib/homelab/homepage -maxdepth 1 -type f -name "*.yaml" -delete
    cp -L ${../../configs/homelab/homepage}/*.yaml /var/lib/homelab/homepage/
    chmod u+w /var/lib/homelab/homepage/*.yaml
  '';

  # Containers
  virtualisation.oci-containers.containers."glances" = {
    image = "docker.io/nicolargo/glances:latest-full";
    environment = {
      "GLANCES_OPT" = "-w";
    };
    volumes = [
      "/etc/os-release:/etc/os-release:ro"
      # podman's socket speaks the Docker API, but homepage's config/docker.yaml and
      # glances both look for it at the conventional path, so keep the container
      # side unchanged and only swap the host side.
      "/run/podman/podman.sock:/var/run/docker.sock:ro"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-glances" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-homepage-root.target"
    ];
    wantedBy = [
      "podman-compose-homepage-root.target"
    ];
  };
  virtualisation.oci-containers.containers."homepage" = {
    image = "ghcr.io/gethomepage/homepage:latest";
    environment = {
      "HOMEPAGE_ALLOWED_HOSTS" = "*";
      # Host networking, so the container listens on the lazy proxy's upstream
      # port directly instead of a published 18300->3000 mapping.
      "PORT" = "18300";
    };
    volumes = [
      # Contents are copied by preStart from the repo (configs/homelab/homepage). It used
      # to be hand-edited files under /var/lib, which meant fixing the old host's IPs
      # after every migration.
      "/var/lib/homelab/homepage:/app/config:rw"
      # podman's socket speaks the Docker API, but homepage's config/docker.yaml and
      # glances both look for it at the conventional path, so keep the container
      # side unchanged and only swap the host side.
      "/run/podman/podman.sock:/var/run/docker.sock:ro"
    ];
    log-driver = "journald";
    # Host network, like glances. services.yaml's siteMonitor and widgets.yaml's
    # glances point at 127.0.0.1:<port>, and most of those services bind loopback
    # only. On the bridge network 127.0.0.1 was the container itself, so every
    # status tile showed 500 (noticed 2026-09-26; broken since the migration
    # rewrote the old CT101 addresses to loopback).
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-homepage" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      # Both are woken together by the lazy socket. Without this ordering homepage's
      # first widget fetches race glances' web server and log ECONNREFUSED 127.0.0.1:61208.
      "podman-glances.service"
    ];
    partOf = [
      "podman-compose-homepage-root.target"
    ];
    wantedBy = [
      "podman-compose-homepage-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-homepage-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
      # The socket-activated lazy target owns the containers now. Retire a
      # compose target left active by an older generation so rebuilds cannot
      # wake Homepage and Glances behind its back.
      StopWhenUnneeded = true;
    };
    wantedBy = [ ];
  };
}
