# Generated by compose2nix from /opt/stacks/jellyfin/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/jellyfin, /mnt/jellyfin-media became
# /srv, and the docker socket became podman's. Not regenerated by anything — the
# compose file it came from dies with Proxmox, so this is the source of truth now.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "lscr.io/linuxserver/jellyfin:latest";
    environment = {
      "PGID" = "0";
      "PUID" = "0";
      "TZ" = "Asia/Tokyo";
    };
    volumes = [
      "/var/lib/homelab/jellyfin/cache:/cache:rw"
      "/var/lib/homelab/jellyfin/config:/config:rw"
      "/srv:/media:rw"
    ];
    ports = [
      "8096:8096/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--network-alias=jellyfin"
      "--network=jellyfin_default"
    ];
  };
  systemd.services."podman-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-jellyfin_default.service"
    ];
    requires = [
      "podman-network-jellyfin_default.service"
    ];
    partOf = [
      "podman-compose-jellyfin-root.target"
    ];
    wantedBy = [
      "podman-compose-jellyfin-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-jellyfin_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f jellyfin_default";
    };
    script = ''
      podman network inspect jellyfin_default || podman network create jellyfin_default
    '';
    partOf = [ "podman-compose-jellyfin-root.target" ];
    wantedBy = [ "podman-compose-jellyfin-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-jellyfin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
