# Generated by compose2nix from /opt/stacks/matrix/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/matrix, /mnt/jellyfin-media became
# /srv, and every value that was interpolated from the stack's .env was dropped so
# that environmentFiles supplies it at runtime — see README.md for the keys each
# file must define. Nothing regenerates this; the compose file dies with Proxmox.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."conduit" = {
    image = "matrixconduit/matrix-conduit:latest";
    environmentFiles = [ "/var/lib/secrets/matrix.env" ];
    environment = {
      "CONDUIT_ADDRESS" = "0.0.0.0";
      "CONDUIT_ALLOW_CHECK_FOR_UPDATES" = "false";
      "CONDUIT_ALLOW_FEDERATION" = "true";
      "CONDUIT_ALLOW_REGISTRATION" = "false";
      "CONDUIT_CONFIG" = "";
      "CONDUIT_DATABASE_BACKEND" = "rocksdb";
      "CONDUIT_DATABASE_PATH" = "/var/lib/matrix-conduit/";
      "CONDUIT_MAX_REQUEST_SIZE" = "20000000";
      "CONDUIT_PORT" = "6167";
      "CONDUIT_SERVER_NAME" = "gapul.net";
      "CONDUIT_TRUSTED_SERVERS" = "[\"matrix.org\"]";
    };
    volumes = [
      "/var/lib/homelab/matrix/cw-data:/var/lib/matrix-conduit:rw"
    ];
    ports = [
      "8008:6167/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=conduit"
      "--network=matrix_default"
    ];
  };
  systemd.services."podman-conduit" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-matrix_default.service"
    ];
    requires = [
      "podman-network-matrix_default.service"
    ];
    partOf = [
      "podman-compose-matrix-root.target"
    ];
    wantedBy = [
      "podman-compose-matrix-root.target"
    ];
  };
  virtualisation.oci-containers.containers."mautrix-discord" = {
    image = "dock.mau.dev/mautrix/discord:latest";
    environmentFiles = [ "/var/lib/secrets/matrix.env" ];
    volumes = [
      "/var/lib/homelab/matrix/bridges/discord:/data:rw"
    ];
    ports = [
      "29334:29334/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mautrix-discord"
      "--network=matrix_default"
    ];
  };
  systemd.services."podman-mautrix-discord" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-matrix_default.service"
    ];
    requires = [
      "podman-network-matrix_default.service"
    ];
    partOf = [
      "podman-compose-matrix-root.target"
    ];
    wantedBy = [
      "podman-compose-matrix-root.target"
    ];
  };
  virtualisation.oci-containers.containers."mautrix-meta" = {
    image = "dock.mau.dev/mautrix/meta:latest";
    environmentFiles = [ "/var/lib/secrets/matrix.env" ];
    volumes = [
      "/var/lib/homelab/matrix/bridges/meta:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mautrix-meta"
      "--network=matrix_default"
    ];
  };
  systemd.services."podman-mautrix-meta" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-matrix_default.service"
    ];
    requires = [
      "podman-network-matrix_default.service"
    ];
    partOf = [
      "podman-compose-matrix-root.target"
    ];
    wantedBy = [
      "podman-compose-matrix-root.target"
    ];
  };
  virtualisation.oci-containers.containers."mautrix-signal" = {
    image = "dock.mau.dev/mautrix/signal:latest";
    environmentFiles = [ "/var/lib/secrets/matrix.env" ];
    volumes = [
      "/var/lib/homelab/matrix/bridges/signal:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mautrix-signal"
      "--network=matrix_default"
    ];
  };
  systemd.services."podman-mautrix-signal" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-matrix_default.service"
    ];
    requires = [
      "podman-network-matrix_default.service"
    ];
    partOf = [
      "podman-compose-matrix-root.target"
    ];
    wantedBy = [
      "podman-compose-matrix-root.target"
    ];
  };
  virtualisation.oci-containers.containers."mautrix-slack" = {
    image = "dock.mau.dev/mautrix/slack:latest";
    environmentFiles = [ "/var/lib/secrets/matrix.env" ];
    volumes = [
      "/var/lib/homelab/matrix/bridges/slack:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mautrix-slack"
      "--network=matrix_default"
    ];
  };
  systemd.services."podman-mautrix-slack" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-matrix_default.service"
    ];
    requires = [
      "podman-network-matrix_default.service"
    ];
    partOf = [
      "podman-compose-matrix-root.target"
    ];
    wantedBy = [
      "podman-compose-matrix-root.target"
    ];
  };
  virtualisation.oci-containers.containers."mautrix-telegram" = {
    image = "dock.mau.dev/mautrix/telegram:latest";
    environmentFiles = [ "/var/lib/secrets/matrix.env" ];
    volumes = [
      "/var/lib/homelab/matrix/bridges/telegram:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mautrix-telegram"
      "--network=matrix_default"
    ];
  };
  systemd.services."podman-mautrix-telegram" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-matrix_default.service"
    ];
    requires = [
      "podman-network-matrix_default.service"
    ];
    partOf = [
      "podman-compose-matrix-root.target"
    ];
    wantedBy = [
      "podman-compose-matrix-root.target"
    ];
  };
  virtualisation.oci-containers.containers."mautrix-twitter" = {
    image = "dock.mau.dev/mautrix/twitter:latest";
    environmentFiles = [ "/var/lib/secrets/matrix.env" ];
    volumes = [
      "/var/lib/homelab/matrix/bridges/twitter:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mautrix-twitter"
      "--network=matrix_default"
    ];
  };
  systemd.services."podman-mautrix-twitter" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-matrix_default.service"
    ];
    requires = [
      "podman-network-matrix_default.service"
    ];
    partOf = [
      "podman-compose-matrix-root.target"
    ];
    wantedBy = [
      "podman-compose-matrix-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-matrix_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f matrix_default";
    };
    script = ''
      podman network inspect matrix_default || podman network create matrix_default
    '';
    partOf = [ "podman-compose-matrix-root.target" ];
    wantedBy = [ "podman-compose-matrix-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-matrix-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
