# Generated by compose2nix from /opt/stacks/miniflux/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/miniflux, /mnt/jellyfin-media became
# /srv, and every value that was interpolated from the stack's .env was dropped so
# that environmentFiles supplies it at runtime — see README.md for the keys each
# file must define. Nothing regenerates this; the compose file dies with Proxmox.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."miniflux" = {
    image = "ghcr.io/miniflux/miniflux:latest";
    environmentFiles = [ "/var/lib/secrets/miniflux.env" ];
    environment = {
      "ADMIN_USERNAME" = "admin";
      "BASE_URL" = "https://rss.gapul.net/";
      "CREATE_ADMIN" = "1";
      "RUN_MIGRATIONS" = "1";
      # 自前の RSSHub を読むために必要。miniflux は既定で私有アドレスへの取得を
      # SSRF 対策として拒否する (`refusing to access private network host`)。
      # 同じ箱の rsshub は podman ネットワーク越しの私有アドレスにしかいないので、
      # これが無いと自前 RSSHub のフィードが一件も更新されない。実際、移行後
      # ずっと日経のフィードが失敗し続けていた。
      #
      # フィードの URL を決めるのは自分だけなので、SSRF の想定脅威はここでは薄い。
      "FETCHER_ALLOW_PRIVATE_NETWORKS" = "1";
    };
    ports = [
      "8081:8080/tcp"
    ];
    dependsOn = [
      "miniflux-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=miniflux"
      "--network=miniflux_default"
    ];
  };
  systemd.services."podman-miniflux" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-miniflux_default.service"
    ];
    requires = [
      "podman-network-miniflux_default.service"
    ];
    partOf = [
      "podman-compose-miniflux-root.target"
    ];
    wantedBy = [
      "podman-compose-miniflux-root.target"
    ];
  };
  virtualisation.oci-containers.containers."miniflux-db" = {
    image = "docker.io/library/postgres:16-alpine";
    environmentFiles = [ "/var/lib/secrets/miniflux.env" ];
    environment = {
      "POSTGRES_DB" = "miniflux";
      "POSTGRES_USER" = "miniflux";
    };
    volumes = [
      "/var/lib/homelab/miniflux/db:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"pg_isready\", \"-U\", \"miniflux\"]"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=miniflux_default"
    ];
  };
  systemd.services."podman-miniflux-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-miniflux_default.service"
    ];
    requires = [
      "podman-network-miniflux_default.service"
    ];
    partOf = [
      "podman-compose-miniflux-root.target"
    ];
    wantedBy = [
      "podman-compose-miniflux-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-miniflux_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f miniflux_default";
    };
    script = ''
      podman network inspect miniflux_default || podman network create miniflux_default
    '';
    partOf = [ "podman-compose-miniflux-root.target" ];
    wantedBy = [ "podman-compose-miniflux-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-miniflux-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
