# Generated by compose2nix from /opt/stacks/navidrome/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/navidrome, /mnt/jellyfin-media became
# /srv, and the docker socket became podman's. Not regenerated by anything — the
# compose file it came from dies with Proxmox, so this is the source of truth now.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."navidrome" = {
    image = "docker.io/deluan/navidrome:latest";
    environment = {
      "ND_LOGLEVEL" = "info";
      "ND_SCANSCHEDULE" = "1h";
      "TZ" = "Asia/Tokyo";
    };
    volumes = [
      "/var/lib/homelab/navidrome/data:/data:rw"
      "/srv/music:/music:ro"
    ];
    ports = [
      "4533:4533/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=navidrome"
      "--network=navidrome_default"
    ];
  };
  systemd.services."podman-navidrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-navidrome_default.service"
    ];
    requires = [
      "podman-network-navidrome_default.service"
    ];
    partOf = [
      "podman-compose-navidrome-root.target"
    ];
    wantedBy = [
      "podman-compose-navidrome-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-navidrome_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f navidrome_default";
    };
    script = ''
      podman network inspect navidrome_default || podman network create navidrome_default
    '';
    partOf = [ "podman-compose-navidrome-root.target" ];
    wantedBy = [ "podman-compose-navidrome-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-navidrome-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
