# Generated by compose2nix from /opt/stacks/ntfy/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/ntfy, /mnt/jellyfin-media became
# /srv, and the docker socket became podman's. Not regenerated by anything — the
# compose file it came from dies with Proxmox, so this is the source of truth now.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."ntfy" = {
    image = "binwiederhier/ntfy:latest";
    environment = {
      "TZ" = "Asia/Tokyo";
    };
    volumes = [
      "/var/lib/homelab/ntfy/cache:/var/cache/ntfy:rw"
      "/var/lib/homelab/ntfy/lib:/var/lib/ntfy:rw"
      "/var/lib/homelab/ntfy/server.yml:/etc/ntfy/server.yml:rw"
    ];
    ports = [
      "8082:80/tcp"
    ];
    cmd = [ "serve" ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=wget -q --tries=1 http://127.0.0.1:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true'"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-timeout=10s"
      "--network-alias=ntfy"
      "--network=ntfy_default"
    ];
  };
  systemd.services."podman-ntfy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-ntfy_default.service"
    ];
    requires = [
      "podman-network-ntfy_default.service"
    ];
    partOf = [
      "podman-compose-ntfy-root.target"
    ];
    wantedBy = [
      "podman-compose-ntfy-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-ntfy_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f ntfy_default";
    };
    script = ''
      podman network inspect ntfy_default || podman network create ntfy_default
    '';
    partOf = [ "podman-compose-ntfy-root.target" ];
    wantedBy = [ "podman-compose-ntfy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-ntfy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
