# Generated by compose2nix from /opt/stacks/obsidian-couchdb/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/obsidian-couchdb, /mnt/jellyfin-media became
# /srv, and every value that was interpolated from the stack's .env was dropped so
# that environmentFiles supplies it at runtime — see README.md for the keys each
# file must define. Nothing regenerates this; the compose file dies with Proxmox.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."obsidian-couchdb" = {
    image = "couchdb:3";
    environmentFiles = [ "/var/lib/secrets/obsidian-couchdb.env" ];
    environment = {
    };
    volumes = [
      "/var/lib/homelab/obsidian-couchdb/data:/opt/couchdb/data:rw"
      "/var/lib/homelab/obsidian-couchdb/local.ini:/opt/couchdb/etc/local.d/local.ini:rw"
    ];
    ports = [
      "5984:5984/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=couchdb"
      "--network=obsidian-couchdb_default"
    ];
  };
  systemd.services."podman-obsidian-couchdb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-obsidian-couchdb_default.service"
    ];
    requires = [
      "podman-network-obsidian-couchdb_default.service"
    ];
    partOf = [
      "podman-compose-obsidian-couchdb-root.target"
    ];
    wantedBy = [
      "podman-compose-obsidian-couchdb-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-obsidian-couchdb_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f obsidian-couchdb_default";
    };
    script = ''
      podman network inspect obsidian-couchdb_default || podman network create obsidian-couchdb_default
    '';
    partOf = [ "podman-compose-obsidian-couchdb-root.target" ];
    wantedBy = [ "podman-compose-obsidian-couchdb-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-obsidian-couchdb-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
