# Generated by compose2nix from /opt/stacks/paperless/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/paperless, /mnt/jellyfin-media became
# /srv, and every value that was interpolated from the stack's .env was dropped so
# that environmentFiles supplies it at runtime — see README.md for the keys each
# file must define. Nothing regenerates this; the compose file dies with Proxmox.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."paperless" = {
    image = "ghcr.io/paperless-ngx/paperless-ngx:latest";
    environmentFiles = [ "/var/lib/secrets/paperless.env" ];
    environment = {
      "PAPERLESS_ADMIN_USER" = "gapul";
      # Without this dateparser guesses the language from the OCR text, and noisy Japanese
      # receipts got read as Thai: the eight scans from 2026-08-25 came out dated 2569
      # (Buddhist era).
      "PAPERLESS_DATE_PARSER_LANGUAGES" = "ja+en";
      # Japanese documents write dates year first. With the default DMY, a receipt's address
      # "新宿3-22-12" became the document date 2022-12-03 once Vision OCR read it cleanly.
      "PAPERLESS_DATE_ORDER" = "YMD";
      # Archive layout on disk, so the media volume stays browsable if Paperless itself is gone.
      # OCR goes to Apple Vision on the macmini (home/macmini.nix, vision-ocr), which speaks the
      # Azure Document Intelligence API. The key is PAPERLESS_REMOTE_OCR_API_KEY in paperless.env.
      # A failed remote OCR fails the consumption instead of falling back to tesseract.
      "PAPERLESS_REMOTE_OCR_ENGINE" = "azureai";
      "PAPERLESS_REMOTE_OCR_ENDPOINT" = "https://macmini.tail079f44.ts.net:8930";
      "PAPERLESS_FILENAME_FORMAT" =
        "{{ created_year }}/{{ document_type }}/{{ correspondent }}_{{ title }}";
      "PAPERLESS_OCR_LANGUAGE" = "jpn+eng";
      "PAPERLESS_OCR_LANGUAGES" = "jpn eng";
      "PAPERLESS_REDIS" = "redis://broker:6379";
      "PAPERLESS_TASK_WORKERS" = "1";
      "PAPERLESS_TIME_ZONE" = "Asia/Tokyo";
      "PAPERLESS_URL" = "https://paperless.gapul.net";
      "PAPERLESS_WEBSERVER_WORKERS" = "1";
    };
    volumes = [
      "/var/lib/homelab/paperless/consume:/usr/src/paperless/consume:rw"
      "/var/lib/homelab/paperless/export:/usr/src/paperless/export:rw"
      "paperless_data:/usr/src/paperless/data:rw"
      "paperless_media:/usr/src/paperless/media:rw"
    ];
    # Loopback high port behind the lazy-http-services socket; Caddy keeps talking to
    # 127.0.0.1:8097, which is now the systemd socket that wakes the container.
    ports = [
      "127.0.0.1:18097:8000/tcp"
    ];
    dependsOn = [
      "paperless-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=webserver"
      "--network=paperless_default"
      # The 3.x image dropped its HEALTHCHECK, and backup.nix waits on `podman healthcheck run
      # paperless` before dumping the database; without a check every nightly backup failed
      # (2026-10-01). A 302 to the login page counts as up.
      "--health-cmd=curl -fs -o /dev/null --max-time 5 http://localhost:8000"
      # Only for that manual run. A timed check fires while the restarted container is
      # still booting, and switch-to-configuration treats the failed transient unit as
      # fatal, so the daily nixos-upgrade ends up failed (2026-10-07).
      "--health-interval=disable"
    ];
  };
  systemd.services."podman-paperless" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-paperless_default.service"
      "podman-volume-paperless_data.service"
      "podman-volume-paperless_media.service"
    ];
    requires = [
      "podman-network-paperless_default.service"
      "podman-volume-paperless_data.service"
      "podman-volume-paperless_media.service"
    ];
    partOf = [
      "podman-compose-paperless-root.target"
    ];
    wantedBy = [
      "podman-compose-paperless-root.target"
    ];
  };
  virtualisation.oci-containers.containers."paperless-redis" = {
    image = "docker.io/library/redis:7-alpine";
    environmentFiles = [ "/var/lib/secrets/paperless.env" ];
    volumes = [
      "paperless_redisdata:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=broker"
      "--network=paperless_default"
    ];
  };
  systemd.services."podman-paperless-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-paperless_default.service"
      "podman-volume-paperless_redisdata.service"
    ];
    requires = [
      "podman-network-paperless_default.service"
      "podman-volume-paperless_redisdata.service"
    ];
    partOf = [
      "podman-compose-paperless-root.target"
    ];
    wantedBy = [
      "podman-compose-paperless-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-paperless_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f paperless_default";
    };
    script = ''
      podman network inspect paperless_default || podman network create paperless_default
    '';
    partOf = [ "podman-compose-paperless-root.target" ];
    wantedBy = [ "podman-compose-paperless-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-paperless_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect paperless_data || podman volume create paperless_data
    '';
    partOf = [ "podman-compose-paperless-root.target" ];
    wantedBy = [ "podman-compose-paperless-root.target" ];
  };
  systemd.services."podman-volume-paperless_media" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect paperless_media || podman volume create paperless_media
    '';
    partOf = [ "podman-compose-paperless-root.target" ];
    wantedBy = [ "podman-compose-paperless-root.target" ];
  };
  systemd.services."podman-volume-paperless_redisdata" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect paperless_redisdata || podman volume create paperless_redisdata
    '';
    partOf = [ "podman-compose-paperless-root.target" ];
    wantedBy = [ "podman-compose-paperless-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-paperless-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  # The container sleeps when idle (lazy-http-services.nix), so a scan dropped into the
  # inbox by Syncthing would otherwise wait for the next web visit. PathChanged fires on
  # a file being written/renamed into the directory (DirectoryNotEmpty would fire forever
  # because of Syncthing's .stfolder marker). The service holds the lazy target up while
  # files remain, plus a grace period for the last document's OCR round trip.
  systemd.paths.paperless-consume = {
    description = "Wake paperless when a document lands in the consume inbox";
    wantedBy = [ "multi-user.target" ];
    pathConfig.PathChanged = "/var/lib/homelab/paperless/consume";
  };
  systemd.services.paperless-consume = {
    description = "Keep paperless awake while the consume inbox has files";
    requires = [ "lazy-paperless.target" ];
    after = [ "lazy-paperless.target" ];
    serviceConfig.Type = "oneshot";
    script = ''
      # Prune hidden directories too: Syncthing's .stfolder/ holds a marker file whose own
      # name is not dotted, and matching it kept paperless awake forever (2026-09-30).
      while [ -n "$(${pkgs.findutils}/bin/find /var/lib/homelab/paperless/consume -mindepth 1 -name '.*' -prune -o -type f -print -quit)" ]; do
        ${pkgs.coreutils}/bin/sleep 30
      done
      ${pkgs.coreutils}/bin/sleep 120
    '';
  };
}
