# Generated by compose2nix from /opt/stacks/radicale/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/radicale, /mnt/jellyfin-media became
# /srv, and the docker socket became podman's. Not regenerated by anything — the
# compose file it came from dies with Proxmox, so this is the source of truth now.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."radicale" = {
    image = "docker.io/tomsquest/docker-radicale:latest";
    volumes = [
      "/var/lib/homelab/radicale/config:/config:ro"
      "/var/lib/homelab/radicale/data:/data:rw"
    ];
    ports = [
      "5232:5232/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=radicale"
      "--network=radicale_default"
    ];
  };
  systemd.services."podman-radicale" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-radicale_default.service"
    ];
    requires = [
      "podman-network-radicale_default.service"
    ];
    partOf = [
      "podman-compose-radicale-root.target"
    ];
    wantedBy = [
      "podman-compose-radicale-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-radicale_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f radicale_default";
    };
    script = ''
      podman network inspect radicale_default || podman network create radicale_default
    '';
    partOf = [ "podman-compose-radicale-root.target" ];
    wantedBy = [ "podman-compose-radicale-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-radicale-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
