# Generated by compose2nix from /opt/stacks/rsshub/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/rsshub, /mnt/jellyfin-media became
# /srv, and the docker socket became podman's. Not regenerated by anything — the
# compose file it came from dies with Proxmox, so this is the source of truth now.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."rsshub" = {
    image = "diygod/rsshub:latest";
    environment = {
      "CACHE_EXPIRE" = "1800";
      "CACHE_TYPE" = "redis";
      "NODE_ENV" = "production";
      "REDIS_URL" = "redis://redis:6379/";
    };
    ports = [
      "1200:1200/tcp"
    ];
    dependsOn = [
      "rsshub-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=rsshub"
      "--network=rsshub_default"
    ];
  };
  systemd.services."podman-rsshub" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-rsshub_default.service"
    ];
    requires = [
      "podman-network-rsshub_default.service"
    ];
    partOf = [
      "podman-compose-rsshub-root.target"
    ];
    wantedBy = [
      "podman-compose-rsshub-root.target"
    ];
  };
  virtualisation.oci-containers.containers."rsshub-redis" = {
    image = "redis:alpine";
    volumes = [
      "/var/lib/homelab/rsshub/redis:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=redis"
      "--network=rsshub_default"
    ];
  };
  systemd.services."podman-rsshub-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-rsshub_default.service"
    ];
    requires = [
      "podman-network-rsshub_default.service"
    ];
    partOf = [
      "podman-compose-rsshub-root.target"
    ];
    wantedBy = [
      "podman-compose-rsshub-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-rsshub_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f rsshub_default";
    };
    script = ''
      podman network inspect rsshub_default || podman network create rsshub_default
    '';
    partOf = [ "podman-compose-rsshub-root.target" ];
    wantedBy = [ "podman-compose-rsshub-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-rsshub-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
