# Generated by compose2nix from /opt/stacks/vaultwarden/compose.yaml on the old Docker host,
# then hand-adjusted: ./ paths became /var/lib/homelab/vaultwarden, /mnt/jellyfin-media became
# /srv, and every value that was interpolated from the stack's .env was dropped so
# that environmentFiles supplies it at runtime — see README.md for the keys each
# file must define. Nothing regenerates this; the compose file dies with Proxmox.
{
  pkgs,
  lib,
  config,
  ...
}:

{

  # Containers
  virtualisation.oci-containers.containers."vaultwarden" = {
    image = "docker.io/vaultwarden/server:latest";
    environmentFiles = [ "/var/lib/secrets/vaultwarden.env" ];
    environment = {
      "DOMAIN" = "https://vault.gapul.net";
      "SIGNUPS_ALLOWED" = "true";
    };
    volumes = [
      "/var/lib/homelab/vaultwarden/data:/data:rw"
    ];
    ports = [
      "8080:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=vaultwarden"
      "--network=vaultwarden_default"
    ];
  };
  systemd.services."podman-vaultwarden" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-vaultwarden_default.service"
    ];
    requires = [
      "podman-network-vaultwarden_default.service"
    ];
    partOf = [
      "podman-compose-vaultwarden-root.target"
    ];
    wantedBy = [
      "podman-compose-vaultwarden-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-vaultwarden_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f vaultwarden_default";
    };
    script = ''
      podman network inspect vaultwarden_default || podman network create vaultwarden_default
    '';
    partOf = [ "podman-compose-vaultwarden-root.target" ];
    wantedBy = [ "podman-compose-vaultwarden-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-vaultwarden-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
