# Common .gitignore templates for different project types

{ lib, ... }:

{
  # Base .gitignore for all projects
  base = ''
    # Editor directories and files
    .vscode/
    .idea/
    *.swp
    *.swo
    *~

    # OS generated files
    .DS_Store
    .DS_Store?
    ._*
    .Spotlight-V100
    .Trashes
    ehthumbs.db
    Thumbs.db

    # Environment variables
    .env
    .env.local
    .env.*.local

    # Logs
    *.log
    npm-debug.log*
    yarn-debug.log*
    yarn-error.log*
    pnpm-debug.log*

    # Runtime data
    pids
    *.pid
    *.seed
    *.pid.lock

    # Coverage directory used by tools like istanbul
    coverage/
    *.lcov

    # Temporary folders
    tmp/
    temp/
  '';

  # Node.js projects
  nodejs = ''
    # Dependencies
    node_modules/
    jspm_packages/

    # Production build
    dist/
    build/

    # Optional npm cache directory
    .npm

    # Optional eslint cache
    .eslintcache

    # Microbundle cache
    .rpt2_cache/
    .rts2_cache_cjs/
    .rts2_cache_es/
    .rts2_cache_umd/

    # Optional REPL history
    .node_repl_history

    # Output of 'npm pack'
    *.tgz

    # Yarn Integrity file
    .yarn-integrity

    # parcel-bundler cache (https://parceljs.org/)
    .cache
    .parcel-cache

    # Next.js build output
    .next
    out

    # Nuxt.js build / generate output
    .nuxt
    dist

    # Storybook build outputs
    .out
    .storybook-out
    storybook-static
  '';

  # Python projects
  python = ''
    # Byte-compiled / optimized / DLL files
    __pycache__/
    *.py[cod]
    *$py.class

    # C extensions
    *.so

    # Distribution / packaging
    .Python
    build/
    develop-eggs/
    dist/
    downloads/
    eggs/
    .eggs/
    lib/
    lib64/
    parts/
    sdist/
    var/
    wheels/
    *.egg-info/
    .installed.cfg
    *.egg
    MANIFEST

    # PyInstaller
    *.manifest
    *.spec

    # Installer logs
    pip-log.txt
    pip-delete-this-directory.txt

    # Unit test / coverage reports
    htmlcov/
    .tox/
    .nox/
    .coverage
    .coverage.*
    .cache
    nosetests.xml
    coverage.xml
    *.cover
    .hypothesis/
    .pytest_cache/

    # Virtual environments
    .env
    .venv
    env/
    venv/
    ENV/
    env.bak/
    venv.bak/

    # Jupyter Notebook
    .ipynb_checkpoints

    # IPython
    profile_default/
    ipython_config.py

    # pyenv
    .python-version

    # Celery stuff
    celerybeat-schedule
    celerybeat.pid

    # SageMath parsed files
    *.sage.py

    # Spyder project settings
    .spyderproject
    .spyproject

    # Rope project settings
    .ropeproject

    # mkdocs documentation
    /site

    # mypy
    .mypy_cache/
    .dmypy.json
    dmypy.json
  '';

  # Rust projects
  rust = ''
    # Generated by Cargo
    /target/
    **/*.rs.bk

    # Cargo.lock should be committed for applications, not for libraries
    # Cargo.lock

    # These are backup files generated by rustfmt
    **/*.rs.bk

    # MSVC Windows builds of rustc generate these, which store debugging information
    *.pdb
  '';

  # Go projects
  go = ''
    # Binaries for programs and plugins
    *.exe
    *.exe~
    *.dll
    *.so
    *.dylib

    # Test binary, built with `go test -c`
    *.test

    # Output of the go coverage tool
    *.out

    # Dependency directories
    vendor/

    # Go workspace file
    go.work

    # Air live reload
    tmp/
  '';

  # R projects
  r = ''
    # History files
    .Rhistory
    .Rapp.history

    # Session Data files
    .RData
    .RDataTmp

    # User-specific files
    .Ruserdata

    # Example code in package build process
    *-Ex.R

    # Output files from R CMD build
    /*.tar.gz

    # Output files from R CMD check
    /*.Rcheck/

    # RStudio files
    .Rproj.user/
    *.Rproj

    # produced vignettes
    vignettes/*.html
    vignettes/*.pdf

    # OAuth2 token
    .httr-oauth

    # knitr and R markdown default cache directories
    *_cache/
    /cache/

    # Temporary files created by R markdown
    *.utf8.md
    *.knit.md

    # R Environment Variables
    .Renviron

    # pkgdown site
    docs/

    # translation temp files
    po/*~

    # RStudio Connect folder
    rsconnect/
  '';

  # Docker projects
  docker = ''
    # Docker build cache
    .dockerignore
    
    # Docker Compose override files
    docker-compose.override.yml
    docker-compose.override.yaml
    
    # Environment-specific compose files
    docker-compose.*.yml
    docker-compose.*.yaml
    !docker-compose.prod.yml
    !docker-compose.dev.yml
    !docker-compose.test.yml
  '';

  # Data science projects
  datascience = ''
    # Data files
    data/raw/*
    data/external/*
    data/interim/*
    data/processed/*
    !data/raw/.gitkeep
    !data/external/.gitkeep
    !data/interim/.gitkeep
    !data/processed/.gitkeep

    # Model files
    models/*.pkl
    models/*.joblib
    models/*.h5
    models/*.pt
    models/*.pth
    models/*.onnx
    models/*.pb
    models/*.tflite

    # Notebook checkpoints
    .ipynb_checkpoints

    # Experiment tracking
    mlruns/
    .mlflow/
    wandb/
    logs/

    # Large datasets
    *.csv
    *.tsv
    *.parquet
    *.h5
    *.hdf5
    *.arrow
    *.feather

    # Compressed files
    *.zip
    *.tar.gz
    *.rar
    *.7z
  '';

  # Mobile development
  mobile = ''
    # React Native
    node_modules/
    .expo/
    dist/
    npm-debug.*
    *.jks
    *.p8
    *.p12
    *.key
    *.mobileprovision
    *.orig.*
    web-build/

    # Metro
    .metro-health-check*

    # Flutter/Dart
    .dart_tool/
    .flutter-plugins
    .flutter-plugins-dependencies
    .packages
    .pub-cache/
    .pub/
    build/
    flutter_*.png
    flutter_*.ipa
    flutter_*.apk

    # Android
    *.iml
    .gradle
    /local.properties
    /.idea/
    .DS_Store
    /build
    /captures
    .externalNativeBuild
    .cxx
    *.apk
    *.ap_
    *.aab

    # iOS
    *.xcworkspace
    !default.xcworkspace
    *.xcuserstate
    UserInterfaceState.xcuserstate
    project.xcworkspace/
    xcuserdata/
    .build/
    DerivedData/
    *.ipa
    *.dSYM.zip
    *.dSYM

    # Fastlane
    fastlane/report.xml
    fastlane/Preview.html
    fastlane/screenshots/**/*.png
    fastlane/test_output
  '';

  # Generate combined .gitignore for specific project types
  forProject = projectTypes: 
    let
      allTypes = [ "base" ] ++ projectTypes;
      contents = map (type: 
        if builtins.hasAttr type gitignoreTemplates
        then gitignoreTemplates.${type}
        else ""
      ) allTypes;
    in
    lib.concatStringsSep "\n\n" (lib.filter (x: x != "") contents);

  # Common combinations
  webProject = forProject [ "nodejs" ];
  pythonProject = forProject [ "python" "datascience" ];
  mobileProject = forProject [ "nodejs" "mobile" ];
  fullstackProject = forProject [ "nodejs" "docker" ];
}