# 外観
osc=no
border=no
keepaspect-window=no
background-color="#191724"  # Rosé Pine base

# OSD
osd-font="SF Pro Display"
osd-font-size=32
osd-color="#e0def4"         # Rosé Pine text
osd-border-color="#191724"  # Rosé Pine base
osd-border-size=2
osd-bar-align-y=0.95
osd-bar-h=2
osd-bar-w=90

# 音声ファイル表示
force-window=yes
geometry=400x400

# 動画
hwdec=auto
vo=gpu

# スクリーンショット
screenshot-directory=~/Pictures
screenshot-format=png
