# 外観
osc=no
border=no
keepaspect-window=no
background-color="#1a1b26"

# OSD
osd-font="SF Pro Display"
osd-font-size=32
osd-color="#c0caf5"
osd-border-color="#1a1b26"
osd-border-size=2
osd-bar-align-y=0.95
osd-bar-h=2
osd-bar-w=90

# 音声ファイル表示
force-window=yes
geometry=400x400

# 動画
hwdec=auto
vo=gpu

# スクリーンショット
screenshot-directory=~/Pictures
screenshot-format=png
