[projects."/Users/gapul"]
trust_level = "trusted"

[projects."/Users/gapul/Developer/github.com/gapul/week09-submit"]
trust_level = "trusted"

[projects."/Users/gapul/Developer/github.com/ut-is-fl-jikken/week10-gapul"]
trust_level = "trusted"

[projects."/Users/gapul/Developer/github.com/mugen404/prod-record"]
trust_level = "trusted"

[tui]
theme = "catppuccin-mocha"

