# Darwin apps component (ECS: profile). GUI app settings, input methods, plist import.
{
  config,
  pkgs,
  lib,
  ...
}:
{
  # tealdeer: under ~/Library/Application Support (Mac convention)
  home.file."Library/Application Support/tealdeer/config.toml".text = ''
    [updates]
    auto_update = true
    auto_update_interval_hours = 720
    archive_source = "https://github.com/tldr-pages/tldr/releases/latest/download/tldr.zip"
  '';

  # airdrop: CLI helper that pops the native AirDrop recipient window (macOS only).
  # Wired into yazi's `O` (open with) menu via configs/cli/yazi/yazi.toml.
  home.file."bin/airdrop" = {
    source = ../../../configs/bin/airdrop;
    executable = true;
  };

  # espanso: general-purpose snippets (public) — to the Container path on Mac
  home.file."Library/Application Support/espanso/match/base.yml".source =
    ../../../configs/espanso/base.yml;

  # macOS-only SOPS template (espanso's personal is at the Container path)
  sops.templates."espanso-personal.yml" = {
    path = "${config.home.homeDirectory}/Library/Application Support/espanso/match/personal.yml";
    content = ''
      # espanso matches (PRIVATE) — generated by sops.templates. PII is consolidated under pii: in secrets.yaml
      matches:
        - trigger: ":gmail"
          label: "Personal Gmail"
          replace: "${config.sops.placeholder."pii/email_personal"}"
        - trigger: ":umail"
          label: "UTokyo Email"
          replace: "${config.sops.placeholder."pii/email_school"}"
        - trigger: ":wmail"
          label: "Work Email"
          replace: "${config.sops.placeholder."pii/email_work"}"
        - trigger: ":sig"
          label: "Signature"
          replace: |
            ----
            ${config.sops.placeholder."pii/name"}
            ${config.sops.placeholder."pii/email_work"}
    '';
  };

  # macOS-only GUI app config (dotfiles/configs/* → symlink into ~/.config)
  home.file.".config/qmk/qmk.ini".text = ''
    [config]

    [user]
    qmk_home = ${config.home.homeDirectory}/repos/qmk

    [console]

    [general]
  '';

  # karabiner writes back directly to dotfiles (mkOutOfStoreSymlink)
  home.file.".config/karabiner".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.dotfiles/configs/keyboard/karabiner";

  # Hammerspoon: modal keyboard-mouse that doesn't conflict with the Space-Hyper WM band (OmniWM).
  # init.lua sets hs.autoLaunch(true), so once launched it stays resident at login too.
  home.file.".hammerspoon".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.dotfiles/configs/keyboard/hammerspoon";

  # neru: mouse-free full-screen navigation (grid/hints/scroll. Successor to Shortcat).
  # Live-tune config.toml via neru CLI / manual edits, so use the same directory
  # mkOutOfStoreSymlink as karabiner. Runtime cruft is excluded by the bundled .gitignore.
  home.file.".config/neru".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.dotfiles/configs/keyboard/neru";

  # Register neru's launchd residency (launch at login + liveness monitoring) via its native service management.
  # Hand-copying a plist would double-launch alongside the native label com.y3owk1n.neru, so
  # call `neru services install` idempotently. It launches only after config.toml (the symlink above)
  # exists, which also prevents the first-run race of "daemon comes up before config, hotkeys unregistered".
  # Neru.app is a brew cask, so skip until the binary is present (not yet installed).
  home.activation.neruService = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    NERU=/opt/homebrew/bin/neru
    # NOTE: match "not loaded" positively. The unloaded message is "Service not loaded",
    # so a `! grep -qi loaded` test matches both states and never reinstalls.
    if [ -x "$NERU" ] && "$NERU" services status 2>/dev/null | grep -qi "not loaded"; then
      "$NERU" services install || true
    fi
  '';

  # mpv launcher (AppleScript droplet). The mpv binary itself is a brew formula (homebrew.brews
  # in darwin.nix), CLI-only and emits no .app, so this droplet is layered on top for Finder
  # associations / drag-and-drop playback. Its contents just call
  # `on open` → /opt/homebrew/bin/mpv <files> &.
  # Don't set recursive: keep the whole bundle as one symlink to preserve the adhoc signing seal.
  home.file."Applications/mpv.app".source = ../../../configs/media/mpv-app/mpv.app;

  # macSKK / azooKey skkserv: defaults import the sandboxed app's preferences
  home.activation.skkPlistImport = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    /usr/bin/defaults import net.mtgto.inputmethod.macSKK \
      ${../../../configs/ime/skk/macSKK.plist}
    if [ -f /Applications/azooKey\ skkserv.app/Contents/MacOS/azooKey\ skkserv ]; then
      /usr/bin/defaults import io.github.gitusp.azoo-key-skkserv \
        ${../../../configs/ime/skk/azoo-key-skkserv.plist}
    fi
    /usr/bin/killall cfprefsd 2>/dev/null || true
  '';

  # place the macSKK kana-rule (romaji conversion rules)
  # it's a Documents file inside the sandbox Container, not a plist, so apply via an actual copy
  home.activation.skkKanaRule = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    skk_settings="${config.home.homeDirectory}/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Settings"
    if [ -d "$skk_settings" ]; then
      /usr/bin/install -m 644 \
        ${../../../configs/ime/skk/kana-rule.conf} \
        "$skk_settings/kana-rule.conf"
    fi
  '';

  # Maccy (clipboard manager) settings — clipboard history is a separate SQLite file, don't touch it
  home.activation.maccyPlistImport = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    if [ -d "$HOME/Library/Containers/org.p0deje.Maccy" ]; then
      /usr/bin/defaults import org.p0deje.Maccy \
        ${../../../configs/clipboard/maccy/Maccy.plist}
      /usr/bin/killall cfprefsd 2>/dev/null || true
    fi
  '';

  # Enforce Puddle (dynamic wallpaper; self-built MIT fork of Plash) behavior.
  # (Migrated from the old Plash in 2026-07; upstream Plash was removed and consolidated into Puddle.)
  # Puddle keeps its websites (wallpaper definitions) and security-scoped bookmarks on the live side,
  # so a full-replace import would wipe the whole wallpaper set. Surgically write only the 3 keys we want to enforce.
  # (extendPlashBelowMenuBar keeps its key name in Puddle for compatibility.)
  home.activation.puddlePrefs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    if [ -d "$HOME/Library/Containers/net.gapul.Puddle" ]; then
      /usr/bin/defaults write net.gapul.Puddle deactivateOnBattery    -bool true
      /usr/bin/defaults write net.gapul.Puddle extendPlashBelowMenuBar -bool true
      /usr/bin/defaults write net.gapul.Puddle showOnAllSpaces         -bool true
    fi
    /usr/bin/killall cfprefsd 2>/dev/null || true
  '';

  # Skim: VimTeX integration. Inverse search (click PDF → jump to line in Neovim) and auto-reload on save.
  # Surgically write only the target keys so other Skim settings aren't broken.
  home.activation.skimSync = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    /usr/bin/defaults write net.sourceforge.skim-app.skim SKTeXEditorPreset -string Custom
    /usr/bin/defaults write net.sourceforge.skim-app.skim SKTeXEditorCommand -string ${pkgs.neovim}/bin/nvim
    /usr/bin/defaults write net.sourceforge.skim-app.skim SKTeXEditorArguments -string "--headless -c \"VimtexInverseSearch %line '%file'\""
    /usr/bin/defaults write net.sourceforge.skim-app.skim SKAutoReloadFileUpdate -bool true
    /usr/bin/defaults write net.sourceforge.skim-app.skim SKAutoCheckFileUpdate -bool true
    /usr/bin/killall cfprefsd 2>/dev/null || true
  '';

  # Login items: auto-launch resident GUI apps that don't start headless
  home.activation.macosLoginItems = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    LOGIN_APPS=(
      "/Applications/OmniWM.app"
      "/Applications/Ghostty.app"
      "/Applications/Puddle.app"
    )
    for app in "''${LOGIN_APPS[@]}"; do
      name=$(basename "$app" .app)
      if ! /usr/bin/osascript -e "tell application \"System Events\" to (name of login items) contains \"$name\"" 2>/dev/null | grep -q true; then
        /usr/bin/osascript -e "tell application \"System Events\" to make login item at end with properties {path:\"$app\", hidden:false}" >/dev/null 2>&1 || true
      fi
    done
    # Retired login items (apps removed from the declaration): drop stale entries
    for name in AeroSpace; do
      if /usr/bin/osascript -e "tell application \"System Events\" to (name of login items) contains \"$name\"" 2>/dev/null | grep -q true; then
        /usr/bin/osascript -e "tell application \"System Events\" to delete login item \"$name\"" >/dev/null 2>&1 || true
      fi
    done
  '';
}
