# Darwin apps component (ECS: profile). GUI app settings, input methods, plist import.
{
  config,
  pkgs,
  lib,
  ...
}:
{
  # tealdeer: under ~/Library/Application Support (Mac convention)
  home.file."Library/Application Support/tealdeer/config.toml".text = ''
    [updates]
    auto_update = true
    auto_update_interval_hours = 720
    archive_source = "https://github.com/tldr-pages/tldr/releases/latest/download/tldr.zip"
  '';

  # airdrop: CLI helper that pops the native AirDrop recipient window (macOS only).
  # Wired into yazi's `O` (open with) menu via configs/cli/yazi/yazi.toml.
  home.file.".local/bin/airdrop" = {
    source = ../../../configs/bin/airdrop;
    executable = true;
  };

  # ios: drive the iPhone's UI from the Mac (screenshot / tap / type) by talking to
  # WebDriverAgent over the network. The WDA project itself is fetched by `ios bootstrap`
  # rather than vendored here, since it is Appium's tree and only needed on this host.
  home.file.".local/bin/ios" = {
    source = ../../../configs/bin/ios;
    executable = true;
  };

  # droid: the Android half of the same idea. adb does the whole job here, so this is
  # a thin wrapper rather than a server to babysit.
  home.file.".local/bin/droid" = {
    source = ../../../configs/bin/droid;
    executable = true;
  };

  # espanso: general-purpose snippets (public) — to the Container path on Mac
  home.file."Library/Application Support/espanso/match/base.yml".source =
    ../../../configs/espanso/base.yml;

  # espanso resident agent. `espanso service register` writes its own plist with a snapshot of
  # whatever PATH the registering shell had (ours had stale ~/bin and .opam entries baked in),
  # so declare the agent here instead and give it a small explicit PATH — espanso's shell
  # extension resolves commands through it.
  launchd.agents.espanso = {
    enable = true;
    config = {
      ProgramArguments = [
        "/opt/homebrew/bin/espanso"
        "launcher"
      ];
      EnvironmentVariables.PATH = lib.concatStringsSep ":" [
        "/opt/homebrew/bin"
        "/opt/homebrew/sbin"
        "${config.home.homeDirectory}/.local/state/nix/profile/bin"
        "/run/current-system/sw/bin"
        "/usr/bin"
        "/bin"
        "/usr/sbin"
        "/sbin"
      ];
      RunAtLoad = true;
      ProcessType = "Interactive";
      StandardErrorPath = "/tmp/espanso.err";
      StandardOutPath = "/tmp/espanso.out";
    };
  };

  # One-shot migrations: hand-written / tool-registered LaunchAgents that a declared agent replaced.
  # Nix can only declare what it owns, and these plists predate that ownership, so removing them
  # stays imperative — but it is one data-driven list instead of a block per app, and each line
  # carries the date it was retired so the stale ones can be swept out later. Anything older than
  # a year is safe to delete: no machine that far behind is going to be rebuilt from this repo.
  home.activation.retiredLaunchAgents =
    let
      retired = [
        "com.federicoterzi.espanso" # 2026-06, replaced by launchd.agents.espanso
        "com.user.mechvibes-hidden" # 2026-06, Mechvibes is long gone; only failed at every login
        "com.felixkratz.borders" # 2026-07, hand-written plist; borders itself dropped 2026-08 (OmniWM draws it)
        "net.gapul.keebmouse" # 2026-07, replaced by launchd.agents.keebmouse
        # 2026-08, replaced by launchd.agents.sketchybar. Removing the plist is enough for launchd;
        # brew's own bookkeeping is swept by the `brew services cleanup` in `just maintain`.
        "homebrew.mxcl.sketchybar"
        # 2026-08, Google's updater. Chrome here is an automation target (the browser is Zen) and
        # `brew upgrade --cask --greedy` in `just maintain` keeps it current, so a resident agent
        # waking up to check versions buys nothing. Chrome re-installs Keystone whenever it is
        # launched — the loop below runs every activation, which is what keeps this from coming
        # back for good.
        "com.google.GoogleUpdater.wake"
        "com.google.keystone.agent"
        "com.google.keystone.xpcservice"
      ];
    in
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      for label in ${lib.concatStringsSep " " retired}; do
        legacy_plist="$HOME/Library/LaunchAgents/$label.plist"
        if [ -f "$legacy_plist" ]; then
          run /bin/launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
          run rm -f "$legacy_plist"
        fi
      done
      # Keystone re-appears with the next Chrome launch; this keeps it quiet in the meantime.
      run /usr/bin/defaults write com.google.Keystone.Agent checkInterval 0 2>/dev/null || true
    '';

  # macOS-only SOPS template (espanso's personal is at the Container path)
  sops.templates."espanso-personal.yml" = {
    path = "${config.home.homeDirectory}/Library/Application Support/espanso/match/personal.yml";
    content = ''
      # espanso matches (PRIVATE) — generated by sops.templates. PII is consolidated under pii: in secrets.yaml
      matches:
        - trigger: ":gmail"
          label: "Personal Gmail"
          replace: "${config.sops.placeholder."pii/email_personal"}"
        - trigger: ":umail"
          label: "UTokyo Email"
          replace: "${config.sops.placeholder."pii/email_school"}"
        - trigger: ":wmail"
          label: "Work Email"
          replace: "${config.sops.placeholder."pii/email_work"}"
        - trigger: ":sig"
          label: "Signature"
          replace: |
            ----
            ${config.sops.placeholder."pii/name"}
            ${config.sops.placeholder."pii/email_work"}
    '';
  };

  # macOS-only GUI app config (dotfiles/configs/* → symlink into ~/.config)
  home.file.".config/qmk/qmk.ini".text = ''
    [config]

    [user]
    qmk_home = ${config.home.homeDirectory}/repos/qmk

    [console]

    [general]
  '';

  # karabiner writes back directly to dotfiles (mkOutOfStoreSymlink)
  home.file.".config/karabiner".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.dotfiles/configs/keyboard/karabiner";

  # Hammerspoon: modal keyboard-mouse that doesn't conflict with the Space-Hyper WM band (OmniWM).
  # init.lua sets hs.autoLaunch(true), so once launched it stays resident at login too.
  home.file.".hammerspoon".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.dotfiles/configs/keyboard/hammerspoon";

  # neru: mouse-free full-screen navigation (grid/hints/scroll. Successor to Shortcat).
  # Live-tune config.toml via neru CLI / manual edits, so use the same directory
  # mkOutOfStoreSymlink as karabiner. Runtime cruft is excluded by the bundled .gitignore.
  home.file.".config/neru".source =
    config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.dotfiles/configs/keyboard/neru";

  # Register neru's launchd residency (launch at login + liveness monitoring) via its native service management.
  # Hand-copying a plist would double-launch alongside the native label com.y3owk1n.neru, so
  # call `neru services install` idempotently. It launches only after config.toml (the symlink above)
  # exists, which also prevents the first-run race of "daemon comes up before config, hotkeys unregistered".
  # Neru.app is a brew cask, so skip until the binary is present (not yet installed).
  home.activation.neruService = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    NERU=/opt/homebrew/bin/neru
    # NOTE: match "not loaded" positively. The unloaded message is "Service not loaded",
    # so a `! grep -qi loaded` test matches both states and never reinstalls.
    if [ -x "$NERU" ] && "$NERU" services status 2>/dev/null | grep -qi "not loaded"; then
      "$NERU" services install || true
    fi
  '';

  # mpv launcher (AppleScript droplet). The mpv binary itself is a brew formula (homebrew.brews
  # in darwin.nix), CLI-only and emits no .app, so this droplet is layered on top for Finder
  # associations / drag-and-drop playback. Its contents just call
  # `on open` → /opt/homebrew/bin/mpv <files> &.
  #
  # Compiled here rather than committed: the bundle was a Mach-O droplet, an Assets.car and a
  # code-signature seal in the repository, all of which osacompile makes from twenty lines of
  # AppleScript. Rebuilt only when the source or the plist additions change, because compiling
  # it every activation would re-sign it every activation.
  #
  # The icon is committed, unlike the rest of the bundle: it is a source asset, not something
  # osacompile can produce. It is mpv's own logo, rendered from the SVG the brew formula
  # installs (share/icons/hicolor/scalable/apps/mpv.svg). Without it the droplet shows
  # osacompile's stock AppleScript-applet icon, which is what shipped until now.
  # Written to /Applications rather than ~/Applications so every bundle this repo produces sits
  # in one place. home-manager runs as the user, but /Applications is drwxrwxr-x root:admin and
  # the account is in admin, so the activation can write there without sudo.
  home.activation.mpvDroplet = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    app="/Applications/mpv.app"
    # The script carries an @mpv@ placeholder rather than a hard-coded path: mpv moved from brew
    # to nixpkgs, so the binary now lives at a store path that changes with every version.
    # osacompile needs a real file, so substitute into a temporary copy.
    script=$(mktemp -t mpv-applescript)
    ${pkgs.gnused}/bin/sed \
      's|@mpv@|${lib.getExe pkgs.mpv}|' \
      ${../../../configs/media/mpv-app/mpv.applescript} > "$script"
    additions=${../../../configs/media/mpv-app/Info-additions.plist}
    icon=${../../../configs/media/mpv-app/mpv.icns}
    stamp="$app/Contents/Resources/.built-from"
    # $script is a fresh mktemp every run, so stamp on what actually decides the contents:
    # the mpv path baked in, plus the other two committed inputs.
    want="${lib.getExe pkgs.mpv} $additions $icon"

    if [ "$(cat "$stamp" 2>/dev/null)" != "$want" ]; then
      $DRY_RUN_CMD rm -rf "$app"
      $DRY_RUN_CMD /usr/bin/osacompile -o "$app" "$script"
      # `Merge` adds keys and leaves the ones already there alone, so the droplet keeps its
      # executable and its usage descriptions. The document types have to be deleted first for
      # the same reason: osacompile writes an empty list, and a duplicate key is skipped, not
      # replaced (it says so and carries on, which is how this silently shipped nothing).
      $DRY_RUN_CMD /usr/libexec/PlistBuddy -c "Delete :CFBundleDocumentTypes" "$app/Contents/Info.plist" 2>/dev/null || true
      $DRY_RUN_CMD /usr/libexec/PlistBuddy -c "Merge $additions" "$app/Contents/Info.plist"
      # CFBundleIconName wins over CFBundleIconFile, and osacompile points it at the applet
      # artwork in Assets.car, so the name has to go before the file is worth setting. Both keys
      # already exist, hence Set rather than the Merge above.
      $DRY_RUN_CMD install -m 644 "$icon" "$app/Contents/Resources/mpv.icns"
      $DRY_RUN_CMD /usr/libexec/PlistBuddy -c "Delete :CFBundleIconName" "$app/Contents/Info.plist" 2>/dev/null || true
      $DRY_RUN_CMD /usr/libexec/PlistBuddy -c "Set :CFBundleIconFile mpv" "$app/Contents/Info.plist"
      $DRY_RUN_CMD sh -c "printf '%s' '$want' > '$stamp'"
      # Finder caches document types per bundle; without this the associations appear at the
      # next login instead of now.
      $DRY_RUN_CMD /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$app"
    fi
    rm -f "$script"
  '';

  # macSKK / azooKey skkserv: defaults import the sandboxed app's preferences
  home.activation.skkPlistImport = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    /usr/bin/defaults import net.mtgto.inputmethod.macSKK \
      ${../../../configs/ime/skk/macSKK.plist}
    if [ -f /Applications/azooKey\ skkserv.app/Contents/MacOS/azooKey\ skkserv ]; then
      /usr/bin/defaults import io.github.gitusp.azoo-key-skkserv \
        ${../../../configs/ime/skk/azoo-key-skkserv.plist}
    fi
    /usr/bin/killall cfprefsd 2>/dev/null || true
  '';

  # place the macSKK kana-rule (romaji conversion rules)
  # it's a Documents file inside the sandbox Container, not a plist, so apply via an actual copy
  home.activation.skkKanaRule = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    skk_settings="${config.home.homeDirectory}/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Settings"
    if [ -d "$skk_settings" ]; then
      /usr/bin/install -m 644 \
        ${../../../configs/ime/skk/kana-rule.conf} \
        "$skk_settings/kana-rule.conf"
    fi
  '';

  # Maccy (clipboard manager) settings — clipboard history is a separate SQLite file, don't touch it
  home.activation.maccyPlistImport = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    if [ -d "$HOME/Library/Containers/org.p0deje.Maccy" ]; then
      /usr/bin/defaults import org.p0deje.Maccy \
        ${../../../configs/clipboard/maccy/Maccy.plist}
      /usr/bin/killall cfprefsd 2>/dev/null || true
    fi
  '';

  # (Skim's VimTeX keys and Puddle's three behavior keys moved to
  #  system.defaults.CustomUserPreferences in hosts/darwin.nix — same `defaults write`, declared.)

  # Login items: auto-launch resident GUI apps that don't start headless
  home.activation.macosLoginItems = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    # The list below is what the machine actually had; it used to be three entries while the
    # other ten were registered by hand or by each app's own "launch at login" toggle, so a
    # fresh machine came up missing them. Adding is idempotent (existing entries are skipped).
    LOGIN_APPS=(
      "/Applications/OmniWM.app"
      # OmniWM has no exec action, so everything that used to be an aerospace
      # after-startup/exec binding lives in Hammerspoon instead (close, new Ghostty window,
      # display mirroring, moving a workspace to the next monitor, the cmd-m/cmd-h swallows).
      # It was running here but undeclared: a fresh machine would come up with those keys
      # silently dead, which is exactly the hole this list exists to close.
      "/Applications/Hammerspoon.app"
      "/Applications/Ghostty.app"
      "/Applications/Nix Apps/Puddle.app" # nix パッケージ化したので Nix Apps 側
      "/Applications/Thaw.app"                # menu bar management
      "/Applications/azooKey skkserv.app"     # SKK conversion server for macSKK
      "/Applications/Maccy.app"               # clipboard history
      "/Applications/LuLu.app"                # outbound firewall
      "/Applications/KDE Connect.app"         # phone integration
      "/Applications/ActivityWatch.app"       # time tracking
      "/Applications/Obsidian.app"            # notes (LiveSync keeps running in the background)
      "/Applications/Zen.app"                 # browser
    )
    # Registration goes through System Events, so it silently does nothing until this process has
    # Automation permission. Report what failed instead of swallowing it — the old `|| true` made a
    # denied TCC prompt look exactly like a successful run.
    failed=""
    for app in "''${LOGIN_APPS[@]}"; do
      name=$(basename "$app" .app)
      # Compare the registered path, not just the name. Matching on the name alone meant a moved
      # app kept its stale entry forever: Puddle became a nix package, the declaration moved to
      # /Applications/Nix Apps, and the login item still pointed at the deleted
      # /Applications/Puddle.app — `path of login item` answered `missing value` and nothing
      # noticed. A wrong path is worse than a missing one, since it fails silently at login.
      current=$(/usr/bin/osascript -e "tell application \"System Events\" to get path of login item \"$name\"" 2>/dev/null)
      if [ "$current" = "$app" ]; then
        continue
      fi
      if [ ! -d "$app" ]; then
        continue # not installed on this machine yet; the cask will bring it, next rebuild registers it
      fi
      if [ -n "$current" ]; then
        /usr/bin/osascript -e "tell application \"System Events\" to delete login item \"$name\"" >/dev/null 2>&1 || true
      fi
      /usr/bin/osascript -e "tell application \"System Events\" to make login item at end with properties {path:\"$app\", hidden:false}" >/dev/null 2>&1 ||
        failed="$failed $name"
    done
    if [ -n "$failed" ]; then
      warnEcho "login items could not be registered:$failed"
      warnEcho "  (grant Automation → System Events, then re-run \`just rebuild\`)"
    fi
    # Retired login items (apps removed from the declaration): drop stale entries.
    #   Bitwarden  — SSH keys moved to the Secure Enclave, so nothing needs the vault at login
    #                any more; it is opened by hand when the vault is actually wanted.
    #   Neru       — its own launchd label (com.y3owk1n.neru, installed by `neru services install`
    #                in home.activation.neruService above) already keeps it resident. Registering
    #                the app here as well started a second copy: two `neru` processes, one under
    #                the native label and one under `application.com.y3owk1n.neru…`.
    #   NTKDaemon  — Native Instruments' installer registers it; the daemon is started on demand
    #                by the `na` wrapper now (see launchd.agents.ntkdaemon in home/darwin.nix),
    #                so it has no reason to run from login until Native Access is used.
    #   NIHardware… — the other half of the same NI leftover, and this one has nothing behind it at
    #                all: the agent bundle is gone from every path its installer uses, so the login
    #                item resolved to a missing value and started nothing every morning.
    for name in AeroSpace Bitwarden Neru NTKDaemon NIHardwareAgent; do
      if /usr/bin/osascript -e "tell application \"System Events\" to (name of login items) contains \"$name\"" 2>/dev/null | grep -q true; then
        /usr/bin/osascript -e "tell application \"System Events\" to delete login item \"$name\"" >/dev/null 2>&1 || true
      fi
    done
  '';
}
