# SketchyBar NG Configuration - FelixKratz Version
# Advanced SketchyBar setup with AI integration and modern features
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.dotfiles.sketchybar;
  
  # Helper function to convert color scheme to SketchyBar format
  mkSketchyBarColors = colors: {
    background = colors.background;
    foreground = colors.foreground;
    primary = colors.primary;
    secondary = colors.secondary;
    accent = colors.accent;
    warning = colors.warning;
    error = colors.error;
    success = colors.success;
  };
  
  # Default color scheme (Catppuccin Mocha)
  defaultColors = mkSketchyBarColors {
    background = "0xff1e1e2e";
    foreground = "0xffcdd6f4";
    primary = "0xfff38ba8";
    secondary = "0xff89b4fa";
    accent = "0xffa6e3a1";
    warning = "0xfff9e2af";
    error = "0xfff38ba8";
    success = "0xffa6e3a1";
  };
in
{
  options.dotfiles.sketchybar = {
    enable = mkEnableOption "SketchyBar NG (FelixKratz version)";
    
    theme = mkOption {
      type = types.enum [ "catppuccin-mocha" "catppuccin-latte" "nord" "tokyo-night" "custom" ];
      default = "catppuccin-mocha";
      description = "SketchyBar color theme";
    };
    
    position = mkOption {
      type = types.enum [ "top" "bottom" ];
      default = "top";
      description = "SketchyBar position on screen";
    };
    
    height = mkOption {
      type = types.int;
      default = 28;
      description = "SketchyBar height in pixels";
    };
    
    aiIntegration = mkOption {
      type = types.bool;
      default = true;
      description = "Enable AI-powered SketchyBar features";
    };
    
    modules = {
      system = mkEnableOption "System information modules" // { default = true; };
      media = mkEnableOption "Media control modules" // { default = true; };
      weather = mkEnableOption "Weather information module" // { default = false; };
      crypto = mkEnableOption "Cryptocurrency price module" // { default = false; };
      network = mkEnableOption "Network status module" // { default = true; };
      git = mkEnableOption "Git status module" // { default = true; };
      docker = mkEnableOption "Docker container status" // { default = true; };
      bluetooth = mkEnableOption "Bluetooth status module" // { default = true; };
      wifi = mkEnableOption "WiFi status module" // { default = true; };
      vpn = mkEnableOption "VPN status module" // { default = true; };
      spaces = mkEnableOption "Workspace/Space management" // { default = true; };
    };
    
    animations = mkOption {
      type = types.bool;
      default = true;
      description = "Enable smooth animations";
    };
    
    notchSupport = mkOption {
      type = types.bool;
      default = true;
      description = "Enable MacBook notch support";
    };
    
    aiFeatures = {
      smartNotifications = mkEnableOption "AI-powered smart notifications";
      contextualInfo = mkEnableOption "Context-aware information display";
      intelligentHiding = mkEnableOption "Intelligent auto-hide based on usage";
      voiceControl = mkEnableOption "Voice control integration";
    };
  };

  config = mkIf cfg.enable {
    # Ensure sketchybar is installed via homebrew (already configured in system/default.nix)
    # homebrew.brews = [ "sketchybar" ];
    
    # SketchyBar configuration directory
    home-manager.users.yuki.home.file.".config/sketchybar" = {
      recursive = true;
      source = ./config;
    };
    
    # Main SketchyBar configuration
    home-manager.users.yuki.home.file.".config/sketchybar/sketchybarrc" = {
      executable = true;
      text = ''
        #!/bin/bash
        # SketchyBar NG Configuration
        # Generated by Nix dotfiles system
        
        source "$CONFIG_DIR/colors.sh" # Loads all defined colors
        source "$CONFIG_DIR/icons.sh" # Loads all defined icons
        
        ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
        PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored
        
        ##### Bar Appearance #####
        sketchybar --bar height=${toString cfg.height} \
                         blur_radius=30 \
                         position=${cfg.position} \
                         sticky=off \
                         padding_left=10 \
                         padding_right=10 \
                         color=$BAR_COLOR \
                         ${optionalString cfg.notchSupport "notch_width=200"} \
                         ${optionalString cfg.animations "y_offset=-5"}
        
        ##### Changing Defaults #####
        sketchybar --default icon.font="SF Pro:Semibold:15.0" \
                             icon.color=$ICON_COLOR \
                             label.font="SF Pro:Semibold:15.0" \
                             label.color=$LABEL_COLOR \
                             padding_left=5 \
                             padding_right=5 \
                             label.padding_left=4 \
                             label.padding_right=10 \
                             icon.padding_left=10 \
                             icon.padding_right=4
        
        ##### Adding Mission Control Space Indicators #####
        ${optionalString cfg.modules.spaces ''
          for i in {1..10}; do
            sketchybar --add space space.$i left \
                       --set space.$i space=$i \
                                     icon=$i \
                                     label.font="sketchybar-app-font:Regular:16.0" \
                                     label.padding_right=20 \
                                     label.y_offset=-1 \
                                     script="$PLUGIN_DIR/space.sh" \
                                     click_script="yabai -m space --focus $i"
          done
        ''}
        
        ##### Adding Left Items #####
        ${optionalString cfg.modules.spaces ''
          sketchybar --add item space_separator left \
                     --set space_separator icon=󰇘 \
                                           icon.color=$ACCENT_COLOR \
                                           icon.font="sketchybar-app-font:Regular:16.0" \
                                           label.drawing=off \
                                           background.drawing=off \
                                           script="$PLUGIN_DIR/space.sh" \
                                           click_script="yabai -m space --create"
        ''}
        
        sketchybar --add item front_app left \
                   --set front_app       background.color=$ACCENT_COLOR \
                                         background.corner_radius=6 \
                                         background.height=24 \
                                         background.drawing=on \
                                         label.color=$BAR_COLOR \
                                         label.font="sketchybar-app-font:Regular:16.0" \
                                         icon.color=$BAR_COLOR \
                                         icon.font="sketchybar-app-font:Regular:16.0" \
                                         script="$PLUGIN_DIR/front_app.sh" \
                   --subscribe front_app front_app_switched
        
        ##### Adding Right Items #####
        ${optionalString cfg.modules.git ''
          sketchybar --add item git right \
                     --set git script="$PLUGIN_DIR/git.sh" \
                               update_freq=5 \
                               icon=󰊢 \
                               icon.color=$SECONDARY_COLOR \
                               label.color=$LABEL_COLOR
        ''}
        
        ${optionalString cfg.modules.docker ''
          sketchybar --add item docker right \
                     --set docker script="$PLUGIN_DIR/docker.sh" \
                                  update_freq=10 \
                                  icon=󰡨 \
                                  icon.color=$PRIMARY_COLOR \
                                  label.color=$LABEL_COLOR
        ''}
        
        ${optionalString cfg.modules.network ''
          sketchybar --add item network right \
                     --set network script="$PLUGIN_DIR/network.sh" \
                                   update_freq=5 \
                                   icon=󰖩 \
                                   icon.color=$ACCENT_COLOR \
                                   label.color=$LABEL_COLOR
        ''}
        
        ${optionalString cfg.modules.bluetooth ''
          sketchybar --add item bluetooth right \
                     --set bluetooth script="$PLUGIN_DIR/bluetooth.sh" \
                                     update_freq=3 \
                                     icon=󰂯 \
                                     icon.color=$SECONDARY_COLOR \
                                     label.color=$LABEL_COLOR
        ''}
        
        ${optionalString cfg.modules.wifi ''
          sketchybar --add item wifi right \
                     --set wifi script="$PLUGIN_DIR/wifi.sh" \
                                update_freq=3 \
                                icon=󰖩 \
                                icon.color=$SUCCESS_COLOR \
                                label.color=$LABEL_COLOR
        ''}
        
        ${optionalString cfg.modules.vpn ''
          sketchybar --add item vpn right \
                     --set vpn script="$PLUGIN_DIR/vpn.sh" \
                               update_freq=5 \
                               icon=󰦝 \
                               icon.color=$WARNING_COLOR \
                               label.color=$LABEL_COLOR
        ''}
        
        ${optionalString cfg.modules.system ''
          sketchybar --add item cpu right \
                     --set cpu  script="$PLUGIN_DIR/cpu.sh" \
                                update_freq=2 \
                                icon=󰻠 \
                                icon.color=$WARNING_COLOR \
                                label.color=$LABEL_COLOR
          
          sketchybar --add item memory right \
                     --set memory script="$PLUGIN_DIR/memory.sh" \
                                  update_freq=3 \
                                  icon=󰍛 \
                                  icon.color=$ERROR_COLOR \
                                  label.color=$LABEL_COLOR
        ''}
        
        sketchybar --add item clock right \
                   --set clock   update_freq=10 \
                                 icon=󰅐 \
                                 icon.color=$ICON_COLOR \
                                 script="$PLUGIN_DIR/clock.sh"
        
        sketchybar --add item battery right \
                   --set battery script="$PLUGIN_DIR/battery.sh" \
                                 update_freq=120 \
                   --subscribe battery system_woke power_source_change
        
        ${optionalString cfg.modules.media ''
          sketchybar --add item media right \
                     --set media script="$PLUGIN_DIR/media.sh" \
                                 label.color=$ACCENT_COLOR \
                                 label.max_chars=20 \
                                 icon.padding_left=0 \
                                 scroll_texts=on \
                     --subscribe media media_change
        ''}
        
        ${optionalString cfg.modules.weather ''
          sketchybar --add item weather right \
                     --set weather script="$PLUGIN_DIR/weather.sh" \
                                   update_freq=600 \
                                   icon=󰖙 \
                                   icon.color=$PRIMARY_COLOR \
                                   label.color=$LABEL_COLOR
        ''}
        
        ${optionalString cfg.modules.crypto ''
          sketchybar --add item crypto right \
                     --set crypto script="$PLUGIN_DIR/crypto.sh" \
                                  update_freq=60 \
                                  icon=󰠓 \
                                  icon.color=$WARNING_COLOR \
                                  label.color=$LABEL_COLOR
        ''}
        
        ##### Force all scripts to run the first time (never do this in a script) #####
        sketchybar --update
        
        echo "SketchyBar NG configuration loaded"
      '';
    };
    
    # Color scheme configuration
    home-manager.users.yuki.home.file.".config/sketchybar/colors.sh" = {
      text = let
        colors = if cfg.theme == "catppuccin-mocha" then defaultColors
                else if cfg.theme == "catppuccin-latte" then mkSketchyBarColors {
                  background = "0xffeff1f5";
                  foreground = "0xff4c4f69";
                  primary = "0xffd20f39";
                  secondary = "0xff1e66f5";
                  accent = "0xff40a02b";
                  warning = "0xffdf8e1d";
                  error = "0xffd20f39";
                  success = "0xff40a02b";
                }
                else if cfg.theme == "nord" then mkSketchyBarColors {
                  background = "0xff2e3440";
                  foreground = "0xffd8dee9";
                  primary = "0xff88c0d0";
                  secondary = "0xff81a1c1";
                  accent = "0xffa3be8c";
                  warning = "0xffebcb8b";
                  error = "0xffbf616a";
                  success = "0xffa3be8c";
                }
                else if cfg.theme == "tokyo-night" then mkSketchyBarColors {
                  background = "0xff1a1b26";
                  foreground = "0xffa9b1d6";
                  primary = "0xff7aa2f7";
                  secondary = "0xffbb9af7";
                  accent = "0xff9ece6a";
                  warning = "0xffe0af68";
                  error = "0xfff7768e";
                  success = "0xff9ece6a";
                }
                else defaultColors; # fallback to catppuccin-mocha
      in ''
        #!/bin/bash
        # Color Palette for SketchyBar NG
        # Theme: ${cfg.theme}
        
        # General colors
        export BLACK=0xff181926
        export WHITE=0xffcad3f5
        export RED=0xffed8796
        export GREEN=0xffa6da95
        export BLUE=0xff8aadf4
        export YELLOW=0xffeed49f
        export ORANGE=0xfff5a97f
        export MAGENTA=0xffc6a0f6
        export GREY=0xff939ab7
        export TRANSPARENT=0x00000000
        
        # Bar colors
        export BAR_COLOR=${colors.background}
        export ICON_COLOR=${colors.foreground}
        export LABEL_COLOR=${colors.foreground}
        export BACKGROUND_1=0xff494d64
        export BACKGROUND_2=0xff414559
        
        # Theme colors
        export PRIMARY_COLOR=${colors.primary}
        export SECONDARY_COLOR=${colors.secondary}
        export ACCENT_COLOR=${colors.accent}
        export WARNING_COLOR=${colors.warning}
        export ERROR_COLOR=${colors.error}
        export SUCCESS_COLOR=${colors.success}
        
        # Item specific colors
        export POPUP_BACKGROUND_COLOR=0xff1e2030
        export POPUP_BORDER_COLOR=$WHITE
        export SHADOW_COLOR=$BLACK
      '';
    };
    
    # Icons configuration
    home-manager.users.yuki.home.file.".config/sketchybar/icons.sh" = {
      text = ''
        #!/bin/bash
        # Icon configuration for SketchyBar NG
        
        # General icons
        export LOADING=󰔟
        export APPLE=󰀵
        export PREFERENCES=󰒓
        export ACTIVITY=󰖚
        export LOCK=󰌾
        export BELL=󰂚
        export BELL_DOT=󰅸
        
        # Git icons
        export GIT_ISSUE=󰨞
        export GIT_DISCUSSION=󰊢
        export GIT_PULL_REQUEST=󰙃
        export GIT_COMMIT=󰜘
        export GIT_INDICATOR=󰊢
        
        # Spotify icons
        export SPOTIFY_BACK=󰒮
        export SPOTIFY_PLAY_PAUSE=󰐊
        export SPOTIFY_NEXT=󰒭
        export SPOTIFY_SHUFFLE=󰒝
        export SPOTIFY_REPEAT=󰑖
        
        # System icons
        export CPU=󰻠
        export MEMORY=󰍛
        export DISK=󰋊
        export NETWORK=󰖩
        
        # Battery icons
        export BATTERY_100=󰁹
        export BATTERY_75=󰂀
        export BATTERY_50=󰁿
        export BATTERY_25=󰁽
        export BATTERY_0=󰁺
        export BATTERY_CHARGING=󰂄
        
        # WiFi icons
        export WIFI_CONNECTED=󰖩
        export WIFI_DISCONNECTED=󰖪
        export WIFI_SEARCHING=󰖫
        
        # Volume icons
        export VOLUME_100=󰕾
        export VOLUME_66=󰖀
        export VOLUME_33=󰕿
        export VOLUME_10=󰕿
        export VOLUME_0=󰝟
        
        # Bluetooth icons
        export BLUETOOTH_CONNECTED=󰂯
        export BLUETOOTH_DISCONNECTED=󰂲
        
        # VPN icons
        export VPN_CONNECTED=󰦝
        export VPN_DISCONNECTED=󰦞
        
        # Docker icons
        export DOCKER_RUNNING=󰡨
        export DOCKER_STOPPED=󰅝
        
        # Weather icons
        export WEATHER_CLEAR=󰖙
        export WEATHER_CLOUDY=󰖐
        export WEATHER_RAIN=󰖖
        export WEATHER_SNOW=󰖘
        export WEATHER_STORM=󰖓
        
        # Crypto icons
        export CRYPTO_BTC=󰠓
        export CRYPTO_ETH=󰨩
        export CRYPTO_UP=󰁝
        export CRYPTO_DOWN=󰁅
      '';
    };
    
    # Plugin scripts directory
    home-manager.users.yuki.home.file.".config/sketchybar/plugins" = {
      recursive = true;
      source = ./plugins;
    };
    
    # Items directory
    home-manager.users.yuki.home.file.".config/sketchybar/items" = {
      recursive = true;
      source = ./items;
    };
    
    # Helper scripts
    home-manager.users.yuki.home.file.".config/sketchybar/helpers" = {
      recursive = true;
      source = ./helpers;
    };
    
    # SketchyBar AI integration setup script
    home-manager.users.yuki.home.file."bin/sketchybar-ai-setup" = mkIf cfg.aiIntegration {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # SketchyBar AI Integration Setup
        set -euo pipefail
        
        echo "🤖 Setting up SketchyBar AI Integration"
        echo "====================================="
        
        # Check if Ollama is available
        if command -v ollama-manager &> /dev/null; then
          echo "✅ Ollama Manager: Available"
          
          # Setup AI models for SketchyBar
          if ollama-manager status | grep -q "Service: Running"; then
            echo "🔧 Setting up AI models for SketchyBar..."
            
            # Download lightweight model for SketchyBar
            ollama-manager models pull phi:2.7b
            echo "✅ Lightweight AI model ready for SketchyBar"
          else
            echo "⚠️  Ollama service not running. Starting..."
            ollama-manager start
          fi
        else
          echo "❌ Ollama Manager not found. Installing..."
          echo "💡 Please run: ollama-manager setup"
        fi
        
        # Setup AI notification system
        ${optionalString cfg.aiFeatures.smartNotifications ''
          echo "🔔 Setting up AI-powered notifications..."
          
          # Create AI notification handler
          cat > ~/.config/sketchybar/plugins/ai_notifications.sh << 'EOF'
        #!/bin/bash
        # AI-powered notification handler for SketchyBar
        
        # Get current context
        CURRENT_APP=$(yabai -m query --windows --window | jq -r '.app')
        CURRENT_TIME=$(date '+%H:%M')
        BATTERY_LEVEL=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)
        
        # Create context for AI
        CONTEXT="Current app: $CURRENT_APP, Time: $CURRENT_TIME, Battery: $BATTERY_LEVEL%"
        
        # Process notification with AI (if available)
        if command -v ollama-manager &> /dev/null && ollama-manager status | grep -q "Service: Running"; then
          AI_RESPONSE=$(echo "Based on this context: $CONTEXT. Should I show this notification prominently? Respond with just 'yes' or 'no'." | ollama-manager chat phi:2.7b | tail -1)
          
          if [[ "$AI_RESPONSE" =~ "yes" ]]; then
            sketchybar --set notifications icon.color=0xffed8796 # Red for important
          else
            sketchybar --set notifications icon.color=0xff939ab7 # Grey for less important
          fi
        fi
        EOF
          
          chmod +x ~/.config/sketchybar/plugins/ai_notifications.sh
          echo "✅ AI notifications configured"
        ''}
        
        # Setup intelligent hiding
        ${optionalString cfg.aiFeatures.intelligentHiding ''
          echo "🫥 Setting up intelligent auto-hide..."
          
          cat > ~/.config/sketchybar/plugins/intelligent_hide.sh << 'EOF'
        #!/bin/bash
        # Intelligent auto-hide based on usage patterns
        
        CURRENT_APP=$(yabai -m query --windows --window | jq -r '.app')
        FULLSCREEN=$(yabai -m query --windows --window | jq -r '.["has-fullscreen-zoom"]')
        
        # Define apps that should trigger auto-hide
        FULLSCREEN_APPS=("Final Cut Pro" "Adobe Premiere Pro" "Logic Pro" "Ableton Live" "Steam" "VLC")
        
        SHOULD_HIDE=false
        
        # Check if current app is in fullscreen list
        for app in "''${FULLSCREEN_APPS[@]}"; do
          if [[ "$CURRENT_APP" == "$app" ]]; then
            SHOULD_HIDE=true
            break
          fi
        done
        
        # Hide bar if necessary
        if [[ "$SHOULD_HIDE" == "true" ]] || [[ "$FULLSCREEN" == "true" ]]; then
          sketchybar --bar hidden=on
        else
          sketchybar --bar hidden=off
        fi
        EOF
          
          chmod +x ~/.config/sketchybar/plugins/intelligent_hide.sh
          echo "✅ Intelligent hiding configured"
        ''}
        
        echo ""
        echo "🎉 SketchyBar AI Integration setup complete!"
        echo ""
        echo "🔧 Available AI Features:"
        echo "  🔔 Smart Notifications: Context-aware notification handling"
        echo "  🫥 Intelligent Hiding: Auto-hide based on app usage"
        echo "  📊 Context-aware Info: Dynamic information display"
        echo ""
        echo "💡 Restart SketchyBar to apply changes: brew services restart sketchybar"
      '';
    };
    
    # SketchyBar health check
    home-manager.users.yuki.home.file."bin/sketchybar-health" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail
        
        echo "🎨 SketchyBar NG Health Check"
        echo "============================="
        
        # Check if SketchyBar is installed
        if command -v sketchybar &> /dev/null; then
          echo "✅ SketchyBar: Installed $(sketchybar --version)"
        else
          echo "❌ SketchyBar: Not found"
          echo "💡 Install via: brew install sketchybar"
          exit 1
        fi
        
        # Check if SketchyBar is running
        if pgrep -f sketchybar > /dev/null; then
          echo "✅ SketchyBar: Running"
        else
          echo "⚠️  SketchyBar: Not running"
          echo "💡 Start with: brew services start sketchybar"
        fi
        
        # Check configuration files
        CONFIG_DIR="$HOME/.config/sketchybar"
        if [[ -f "$CONFIG_DIR/sketchybarrc" ]]; then
          echo "✅ Configuration: Present"
        else
          echo "❌ Configuration: Missing"
          echo "💡 Run system rebuild to generate config"
        fi
        
        # Check AI integration
        ${optionalString cfg.aiIntegration ''
          echo ""
          echo "🤖 AI Integration Status:"
          if command -v ollama-manager &> /dev/null; then
            echo "✅ Ollama Manager: Available"
            if ollama-manager status | grep -q "Service: Running"; then
              echo "✅ AI Service: Running"
            else
              echo "⚠️  AI Service: Not running"
            fi
          else
            echo "❌ Ollama Manager: Not available"
          fi
        ''}
        
        # Check enabled modules
        echo ""
        echo "🧩 Enabled Modules:"
        ${optionalString cfg.modules.system "echo \"  ✅ System Information\""}
        ${optionalString cfg.modules.media "echo \"  ✅ Media Controls\""}
        ${optionalString cfg.modules.weather "echo \"  ✅ Weather\""}
        ${optionalString cfg.modules.crypto "echo \"  ✅ Cryptocurrency\""}
        ${optionalString cfg.modules.network "echo \"  ✅ Network Status\""}
        ${optionalString cfg.modules.git "echo \"  ✅ Git Status\""}
        ${optionalString cfg.modules.docker "echo \"  ✅ Docker Status\""}
        ${optionalString cfg.modules.bluetooth "echo \"  ✅ Bluetooth\""}
        ${optionalString cfg.modules.wifi "echo \"  ✅ WiFi\""}
        ${optionalString cfg.modules.vpn "echo \"  ✅ VPN\""}
        ${optionalString cfg.modules.spaces "echo \"  ✅ Workspace Management\""}
        
        echo ""
        echo "⚙️  Configuration:"
        echo "  📍 Position: ${cfg.position}"
        echo "  📏 Height: ${toString cfg.height}px"
        echo "  🎨 Theme: ${cfg.theme}"
        echo "  ✨ Animations: ${if cfg.animations then "Enabled" else "Disabled"}"
        echo "  📱 Notch Support: ${if cfg.notchSupport then "Enabled" else "Disabled"}"
        
        echo ""
        echo "📊 Status: SketchyBar NG ready!"
      '';
    };
    
    # LaunchAgent for SketchyBar
    home-manager.users.yuki.home.file."Library/LaunchAgents/com.felixkratz.sketchybar.plist" = {
      text = ''
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>Label</key>
          <string>com.felixkratz.sketchybar</string>
          <key>ProgramArguments</key>
          <array>
            <string>${pkgs.sketchybar or "/opt/homebrew/bin/sketchybar"}</string>
            <string>--config</string>
            <string>/Users/yuki/.config/sketchybar/sketchybarrc</string>
          </array>
          <key>EnvironmentVariables</key>
          <dict>
            <key>PATH</key>
            <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
            <key>CONFIG_DIR</key>
            <string>/Users/yuki/.config/sketchybar</string>
          </dict>
          <key>RunAtLoad</key>
          <true/>
          <key>KeepAlive</key>
          <true/>
          <key>ProcessType</key>
          <string>Interactive</string>
        </dict>
        </plist>
      '';
    };
    
    # Shell aliases for SketchyBar management
    home-manager.users.yuki.programs.zsh.shellAliases = {
      # SketchyBar management
      sb-restart = "brew services restart sketchybar";
      sb-stop = "brew services stop sketchybar";
      sb-start = "brew services start sketchybar";
      sb-reload = "sketchybar --reload";
      sb-health = "sketchybar-health";
      sb-ai-setup = mkIf cfg.aiIntegration "sketchybar-ai-setup";
      
      # SketchyBar debugging
      sb-debug = "sketchybar --query bar";
      sb-items = "sketchybar --query default";
      sb-config = "cat ~/.config/sketchybar/sketchybarrc";
    };
    
    # Environment variables
    home-manager.users.yuki.home.sessionVariables = {
      SKETCHYBAR_CONFIG_DIR = "$HOME/.config/sketchybar";
      SKETCHYBAR_THEME = cfg.theme;
    };
  };
}