#!/usr/bin/env python3
"""Generate keyball39 keymap.c from the Remap-extracted keymap-export.json.

Every keycode -> QMK symbol mapping below was pulled from Remap's own
authoritative keycode database (keycodeInfo.name / kinds / modifiers), so the
decode is exact rather than guessed. Keyball custom codes (QK_KB_n) are mapped
to the keyball firmware's own #defined names via lib/keyball keycodes.md.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "keymap-export.json")))

# code (int) -> final QMK keymap symbol string
CODE2SYM = {
    0: "XXXXXXX", 1: "_______",
    # basic letters / numbers / symbols / edits / F-keys / arrows
    5: "KC_B", 6: "KC_C", 8: "KC_E", 16: "KC_M", 17: "KC_N", 18: "KC_O",
    19: "KC_P", 20: "KC_Q", 21: "KC_R", 23: "KC_T", 24: "KC_U", 25: "KC_V",
    26: "KC_W", 27: "KC_X", 28: "KC_Y", 29: "KC_Z",
    30: "KC_1", 31: "KC_2", 32: "KC_3", 33: "KC_4", 34: "KC_5", 35: "KC_6",
    36: "KC_7", 37: "KC_8", 38: "KC_9", 39: "KC_0",
    40: "KC_ENT", 42: "KC_BSPC", 43: "KC_TAB",
    45: "KC_MINS", 46: "KC_EQL", 47: "KC_LBRC", 48: "KC_RBRC", 49: "KC_BSLS",
    52: "KC_QUOT", 53: "KC_GRV", 54: "KC_COMM", 55: "KC_DOT", 56: "KC_SLSH",
    58: "KC_F1", 59: "KC_F2", 61: "KC_F4", 63: "KC_F6", 64: "KC_F7",
    65: "KC_F8", 66: "KC_F9", 67: "KC_F10", 68: "KC_F11", 69: "KC_F12",
    79: "KC_RGHT", 80: "KC_LEFT", 81: "KC_DOWN", 82: "KC_UP",
    169: "KC_VOLU", 170: "KC_VOLD", 189: "KC_BRIU", 190: "KC_BRID",
    209: "KC_BTN1", 210: "KC_BTN2", 211: "KC_BTN3",
    224: "KC_LCTL", 226: "KC_LALT", 227: "KC_LGUI", 230: "KC_RALT", 231: "KC_RGUI",
    # shifted basic (LSFT-modified)
    542: "S(KC_1)", 543: "S(KC_2)", 544: "S(KC_3)", 545: "S(KC_4)", 546: "S(KC_5)",
    547: "S(KC_6)", 548: "S(KC_7)", 549: "S(KC_8)", 550: "S(KC_9)", 551: "S(KC_0)",
    558: "S(KC_EQL)", 559: "S(KC_LBRC)", 560: "S(KC_RBRC)", 561: "S(KC_BSLS)",
    563: "S(KC_SCLN)", 564: "S(KC_QUOT)", 565: "S(KC_GRV)", 566: "S(KC_COMM)",
    567: "S(KC_DOT)", 568: "S(KC_SLSH)", 572: "S(KC_F3)", 574: "S(KC_F5)",
    # mod-tap (home row mods etc.)
    8470: "LCTL_T(KC_S)", 8481: "LCTL_T(KC_4)", 8708: "LSFT_T(KC_A)",
    8849: "LSFT_T(KC_LNG2)", 9223: "LALT_T(KC_D)", 10249: "LGUI_T(KC_F)",
    11530: "MT(MOD_LCTL | MOD_LALT | MOD_LGUI, KC_G)",
    12559: "RCTL_T(KC_L)", 12851: "RSFT_T(KC_SCLN)", 13326: "RALT_T(KC_K)",
    14349: "RGUI_T(KC_J)",
    15627: "MT(MOD_RCTL | MOD_RALT | MOD_RGUI, KC_H)",
    # layer-tap
    16682: "LT(1,KC_BSPC)", 16684: "LT(1,KC_SPC)", 16936: "LT(2,KC_ENT)",
    16937: "LT(2,KC_ESC)", 17164: "LT(3,KC_I)", 17195: "LT(3,KC_TAB)",
    # RGB underglow (RGBLIGHT) -- names used by this keyball QMK tree
    30752: "RGB_TOG", 30753: "RGB_MOD", 30754: "RGB_RMOD", 30755: "RGB_HUI",
    30756: "RGB_HUD", 30757: "RGB_SAI", 30758: "RGB_SAD", 30759: "RGB_VAI",
    30760: "RGB_VAD", 30763: "RGB_M_P", 30764: "RGB_M_B", 30765: "RGB_M_R",
    30766: "RGB_M_SW", 30767: "RGB_M_SN", 30768: "RGB_M_K", 30769: "RGB_M_X",
    30770: "RGB_M_G", 30771: "RGB_M_T", 30772: "RGB_M_TW",
    # firmware / keyball custom
    31744: "QK_BOOT",
    32256: "KBC_RST", 32257: "KBC_SAVE", 32258: "CPI_I100", 32259: "CPI_D100",
    32260: "CPI_I1K", 32261: "CPI_D1K", 32264: "SCRL_DVI", 32265: "SCRL_DVD",
    32266: "AML_TO", 32267: "AML_I50", 32268: "AML_D50",
}

# LAYOUT_universal (= LAYOUT_no_ball) argument order, expressed as matrix "row,col".
ORDER = [
    ["0,0","0,1","0,2","0,3","0,4",  "4,4","4,3","4,2","4,1","4,0"],
    ["1,0","1,1","1,2","1,3","1,4",  "5,4","5,3","5,2","5,1","5,0"],
    ["2,0","2,1","2,2","2,3","2,4",  "6,4","6,3","6,2","6,1","6,0"],
    ["3,0","3,1","3,2","3,3","3,4","3,5",  "7,5","7,4","7,3","7,2","7,1","7,0"],
]

def sym(layer, pos):
    code = data["layers"][str(layer)][pos]
    if code not in CODE2SYM:
        raise SystemExit(f"UNKNOWN CODE {code} at layer {layer} pos {pos}")
    return CODE2SYM[code]

def fmt_row(cells):
    return ", ".join(f"{c:>14}" for c in cells)

layers_out = []
for L in range(data["layerCount"]):
    rows = []
    for r in ORDER:
        rows.append("    " + fmt_row([sym(L, p) for p in r]))
    layers_out.append(f"  [{L}] = LAYOUT_universal(\n" + " ,\n".join(rows) + "\n  )")

body = ",\n\n".join(layers_out)

out = f"""// SPDX-License-Identifier: GPL-2.0-or-later
// Keyball39 keymap for gapul -- migrated from Remap/VIA to code.
// Auto-generated by gen_keymap.py from keymap-export.json (extracted from the
// live keyball via Remap). VIA stays enabled so Remap can still tweak keymap
// and lighting on top of this base.

#include QMK_KEYBOARD_H
#include "quantum.h"

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {{
{body}
}};
// clang-format on

layer_state_t layer_state_set_user(layer_state_t state) {{
    // Auto enable scroll mode when the highest layer is 3 (same as stock via keymap)
    keyball_set_scroll_mode(get_highest_layer(state) == 3);
    return state;
}}

#ifdef OLED_ENABLE
#    include "lib/oledkit/oledkit.h"
void oledkit_render_info_user(void) {{
    keyball_oled_render_keyinfo();
    keyball_oled_render_ballinfo();
    keyball_oled_render_layerinfo();
}}
#endif
"""

open(os.path.join(HERE, "keymap.c"), "w").write(out)
print("wrote keymap.c")
print(out)
