// SPDX-License-Identifier: GPL-2.0-or-later
// Keyball39 keymap for gapul -- migrated from Remap/VIA to code.
// Auto-generated by gen_keymap.py from keymap-export.json (extracted from the
// live keyball via Remap). VIA stays enabled so Remap can still tweak keymap
// and lighting on top of this base.

#include QMK_KEYBOARD_H
#include "quantum.h"

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT_universal(
              KC_Q,           KC_W,           KC_E,           KC_R,           KC_T,           KC_Y,           KC_U,     LT(3,KC_I),           KC_O,           KC_P ,
      LSFT_T(KC_A),   LCTL_T(KC_S),   LALT_T(KC_D),   LGUI_T(KC_F), MT(MOD_LCTL | MOD_LALT | MOD_LGUI, KC_G), MT(MOD_RCTL | MOD_RALT | MOD_RGUI, KC_H),   RGUI_T(KC_J),   RALT_T(KC_K),   RCTL_T(KC_L), RSFT_T(KC_SCLN) ,
              KC_Z,           KC_X,           KC_C,           KC_V,           KC_B,           KC_N,           KC_M,        KC_COMM,         KC_DOT,        KC_MINS ,
           KC_LCTL,        KC_LALT,        KC_LGUI,   LT(3,KC_TAB),   LT(1,KC_SPC),   LT(2,KC_ESC),   LT(2,KC_ENT),  LT(1,KC_BSPC), LSFT_T(KC_LNG2),        KC_RALT,        KC_RGUI,        KC_SLSH
  ),

  [1] = LAYOUT_universal(
            KC_GRV,           KC_7,           KC_8,           KC_9,      S(KC_EQL),         KC_EQL,        KC_BSLS,        KC_BTN3,        KC_LBRC,        KC_RBRC ,
              KC_0,   LCTL_T(KC_4),           KC_5,           KC_6,     S(KC_LBRC),     S(KC_RBRC),        KC_BTN1,          KC_UP,        KC_BTN2,        KC_QUOT ,
           S(KC_8),           KC_1,           KC_2,           KC_3,        S(KC_9),        S(KC_0),        KC_LEFT,        KC_DOWN,        KC_RGHT,        KC_SLSH ,
           KC_SLSH,           KC_0,         KC_DOT,         KC_TAB,         KC_ENT,        KC_BSPC,        KC_BRID,        KC_BRIU,        _______,        KC_RALT,        KC_RGUI,     S(KC_SLSH)
  ),

  [2] = LAYOUT_universal(
             KC_F1,          KC_F2,       S(KC_F3),          KC_F4,       S(KC_F5),          KC_F6,          KC_F7,          KC_F8,          KC_F9,         KC_F10 ,
              KC_1,           KC_2,           KC_3,           KC_4,           KC_5,           KC_6,           KC_7,           KC_8,           KC_9,           KC_0 ,
           S(KC_1),        S(KC_2),        S(KC_3),        S(KC_4),        S(KC_5),        S(KC_6),        S(KC_7),        S(KC_8),      S(KC_GRV),         KC_F11 ,
        S(KC_COMM),      S(KC_DOT),     S(KC_BSLS),     S(KC_QUOT),     S(KC_SCLN),     S(KC_QUOT),        KC_VOLD,        KC_VOLU,        _______,        _______,        _______,         KC_F12
  ),

  [3] = LAYOUT_universal(
           RGB_TOG,         AML_TO,        AML_I50,        AML_D50,        _______,        RGB_M_P,        RGB_M_B,        RGB_M_R,       RGB_M_SW,       RGB_M_SN ,
           RGB_MOD,        RGB_HUI,        RGB_SAI,        RGB_VAI,       SCRL_DVI,        RGB_M_K,        RGB_M_X,        RGB_M_G,        RGB_M_T,       RGB_M_TW ,
          RGB_RMOD,        RGB_HUD,        RGB_SAD,        RGB_VAD,       SCRL_DVD,        CPI_D1K,       CPI_D100,       CPI_I100,        CPI_I1K,       KBC_SAVE ,
           QK_BOOT,        KBC_RST,        _______,        _______,        _______,        _______,        _______,        _______,        _______,        _______,        KBC_RST,        QK_BOOT
  )
};
// clang-format on

layer_state_t layer_state_set_user(layer_state_t state) {
    // Auto enable scroll mode when the highest layer is 3 (same as stock via keymap)
    keyball_set_scroll_mode(get_highest_layer(state) == 3);
    return state;
}

#ifdef OLED_ENABLE
#    include "lib/oledkit/oledkit.h"
void oledkit_render_info_user(void) {
    keyball_oled_render_keyinfo();
    keyball_oled_render_ballinfo();
    keyball_oled_render_layerinfo();
}
#endif
