#!/usr/bin/env python3
"""Generate the tmux theme used on hosts that home-manager never touches.

母艦では nix/modules/home/terminal.nix が palettes.json から
~/.config/tmux/{rose-pine,rose-pine-dawn,theme}.conf を生成する。nssh 先の
リモートホストは home-manager を通らないのでそれらが存在せず、tmux.conf 末尾の
`source-file -q ~/.config/tmux/theme.conf` が黙って読み飛ばされ、素の緑の
ステータスバーになっていた。

そこでリポジトリに追跡ファイルとして静的なテーマを 1 枚置く。リモートの
~/.config/tmux は dotfiles への symlink なので、置くだけで解決する。

色は hex ではなく ANSI 番号で置く (2026-08 に hex から変更)。ssh 先には OS の
外観を知る手段が無いが、色を解決するのは接続元の端末なので、母艦の ghostty が
Rose Pine / Rose Pine Dawn を切り替えれば、このステータスバーは side channel
無しで追従する。lazygit / delta / fzf が nix/modules/home/cli.nix で採っている
のと同じ取引で、代償は rose-pine の中間色が 16 色に丸まること。

そのため palettes.json はもう読まない (active を変えてもこのファイルは変わらない)。
生成物であり続けるのは、母艦版 mkTmuxTheme とレイアウトを 1 箇所で揃えたまま
手編集を scripts/check-generated.sh に弾かせるため。

  再生成: python3 scripts/gen-tmux-theme.py
  検査  : python3 scripts/gen-tmux-theme.py --check
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

REPO = pathlib.Path(
    subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()
)
OUT = REPO / "configs/terminals/tmux/theme-remote.conf"


def render() -> str:
    """nix/modules/home/terminal.nix の mkTmuxTheme と同じレイアウトを組み立てる。

    母艦版との差は 3 点:
      - status-right の resurrect 保存時刻を出さない。resurrect-status.sh は
        home-manager の生成物で、リモートには存在しない。
      - 色が hex ではなく ANSI 番号 (docstring 参照)。
      - 母艦版は theme.conf が dark/light 2 枚を切り替えるが、こちらは 1 枚で
        両対応する (端末側が色を差し替えるため切り替える必要が無い)。
    """
    return """\
# tmux theme for hosts that home-manager never touches — generated by
# scripts/gen-tmux-theme.py. DO NOT EDIT BY HAND.
#
# nssh 先 (リモートホスト) 専用。母艦では nix が生成する
# ~/.config/tmux/theme.conf が使われ、こちらは読まれない
# (tmux.conf 側で theme.conf の不在を条件にしている)。
#
# 色は hex ではなく ANSI 番号なので、解決するのは接続元の端末になる。母艦の
# ghostty が Rose Pine / Rose Pine Dawn を切り替えれば、このバーは何も
# 受け取らずにライト/ダークへ追従する。役割 → ANSI の対応は
# windows/terminal/settings.json.tmpl (Windows Terminal のパレット) と同じ:
#
#   0 overlay  1 love  2 pine  3 gold  4 foam  5 iris  6 rose  7 text  8 muted
#
# 背景は `default` = 端末の背景そのもの。rose-pine の subtle / hlMed には
# 対応する ANSI 枠が無いので、それぞれ text / muted に寄せてある。
set -g status-position top
set -g status-interval 5
set -g status-justify left

set -g status-style               "bg=default,fg=colour7"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left  "#[bg=colour2,fg=colour0,bold] #S #[bg=default,fg=colour2]#[default] "
# 母艦版と違い resurrect の保存時刻は出さない (プラグインがリモートに無いため)。
# PREFIX バッジは client_prefix の変化で tmux が再描画するので interval に依らず即座に出る。
set -g status-right "#{?client_prefix,#[bg=colour1#,fg=colour0#,bold] PREFIX #[default] ,}#[fg=colour8]%Y-%m-%d #[fg=colour4]%H:%M "

# inactive / active windows (tabs)
set -g window-status-format         "#[fg=colour8] #I #W "
set -g window-status-current-format "#[bg=colour0,fg=colour5,bold] #I #W "
set -g window-status-separator ""
set -g window-status-activity-style "fg=colour3"

# pane border / message / copy mode
set -g pane-border-style        "fg=colour0"
set -g pane-active-border-style "fg=colour2"
set -g message-style            "bg=colour0,fg=colour7"
set -g message-command-style    "bg=colour0,fg=colour7"
set -g mode-style               "bg=colour8,fg=colour7"
set -g display-panes-active-colour "colour5"
set -g display-panes-colour        "colour8"
set -g clock-mode-colour           "colour4"
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="書き換えずに、生成物が最新かどうかだけ検査する",
    )
    args = ap.parse_args()

    want = render()

    if args.check:
        have = OUT.read_text() if OUT.exists() else ""
        if have != want:
            rel = OUT.relative_to(REPO)
            print(
                f"{rel} が gen-tmux-theme.py と一致しません。"
                " python3 scripts/gen-tmux-theme.py で再生成してください。",
                file=sys.stderr,
            )
            return 1
        return 0

    OUT.write_text(want)
    print(f"wrote {OUT.relative_to(REPO)} (ANSI colours; follows the client terminal)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
