#!/usr/bin/env python3
"""Generate the tmux theme used on hosts that home-manager never touches.

母艦では nix/modules/home/terminal.nix が palettes.json から
~/.config/tmux/{rose-pine,rose-pine-dawn,theme}.conf を生成する。nssh 先の
リモートホストは home-manager を通らないのでそれらが存在せず、tmux.conf 末尾の
`source-file -q ~/.config/tmux/theme.conf` が黙って読み飛ばされ、素の緑の
ステータスバーになっていた。

そこでリポジトリに追跡ファイルとして静的なテーマを 1 枚置く。リモートの
~/.config/tmux は dotfiles への symlink なので、置くだけで解決する。

色は configs/theme/palettes.json (SSO) の active パレットから生成する。手で
書くと母艦側と drift するため。生成物は scripts/check-generated.sh が検査する。

  再生成: python3 scripts/gen-tmux-theme.py
  検査  : python3 scripts/gen-tmux-theme.py --check
"""

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

REPO = pathlib.Path(
    subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()
)
PALETTES = REPO / "configs/theme/palettes.json"
OUT = REPO / "configs/terminals/tmux/theme-remote.conf"


def render(name: str, p: dict[str, str]) -> str:
    """nix/modules/home/terminal.nix の mkTmuxTheme と同じ見た目を組み立てる。

    母艦版との差は 2 点だけ:
      - status-right の resurrect 保存時刻を出さない。resurrect-status.sh は
        home-manager の生成物で、リモートには存在しない。
      - リモートは OS の外観を追えないので active パレット固定 (ライト/ダークの
        自動追従なし)。
    """
    return f"""\
# rose-pine ({name}) — generated by scripts/gen-tmux-theme.py from
# configs/theme/palettes.json. DO NOT EDIT BY HAND.
#
# home-manager を通らないホスト (nssh 先) 専用。母艦では nix が生成する
# ~/.config/tmux/theme.conf が使われ、こちらは読まれない
# (tmux.conf 側で theme.conf の不在を条件にしている)。
set -g status-position top
set -g status-interval 5
set -g status-justify left

set -g status-style               "bg=#{p['base']},fg=#{p['subtle']}"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left  "#[bg=#{p['pine']},fg=#{p['base']},bold] #S #[bg=#{p['base']},fg=#{p['pine']}]#[default] "
# 母艦版と違い resurrect の保存時刻は出さない (プラグインがリモートに無いため)。
# PREFIX バッジは client_prefix の変化で tmux が再描画するので interval に依らず即座に出る。
set -g status-right "#{{?client_prefix,#[bg=#{p['love']}#,fg=#{p['base']}#,bold] PREFIX #[default] ,}}#[fg=#{p['muted']}]%Y-%m-%d #[fg=#{p['foam']}]%H:%M "

# inactive / active windows (tabs)
set -g window-status-format         "#[fg=#{p['muted']}] #I #W "
set -g window-status-current-format "#[bg=#{p['overlay']},fg=#{p['iris']},bold] #I #W "
set -g window-status-separator ""
set -g window-status-activity-style "fg=#{p['gold']}"

# pane border / message / copy mode
set -g pane-border-style        "fg=#{p['overlay']}"
set -g pane-active-border-style "fg=#{p['pine']}"
set -g message-style            "bg=#{p['overlay']},fg=#{p['text']}"
set -g message-command-style    "bg=#{p['overlay']},fg=#{p['text']}"
set -g mode-style               "bg=#{p['hlMed']},fg=#{p['text']}"
set -g display-panes-active-colour "#{p['iris']}"
set -g display-panes-colour        "#{p['muted']}"
set -g clock-mode-colour           "#{p['foam']}"
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="書き換えずに、生成物が最新かどうかだけ検査する",
    )
    args = ap.parse_args()

    data = json.loads(PALETTES.read_text())
    active = data["active"]
    palette = data["palettes"][active]
    want = render(active, palette)

    if args.check:
        have = OUT.read_text() if OUT.exists() else ""
        if have != want:
            rel = OUT.relative_to(REPO)
            print(
                f"{rel} が palettes.json と一致しません。"
                " python3 scripts/gen-tmux-theme.py で再生成してください。",
                file=sys.stderr,
            )
            return 1
        return 0

    OUT.write_text(want)
    print(f"wrote {OUT.relative_to(REPO)} (palette: {active})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
