#!/bin/bash

# Advanced System Optimization Script
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Configure nix build optimization
optimize_nix_builds() {
    log_info "=== Optimizing Nix Build Configuration ==="
    
    local nix_conf="/etc/nix/nix.conf"
    
    # Backup current configuration
    if [[ -f "$nix_conf" ]]; then
        sudo cp "$nix_conf" "${nix_conf}.backup.$(date +%Y%m%d_%H%M%S)"
        log_success "Backed up existing nix.conf"
    fi
    
    # Create optimized nix.conf
    cat << 'EOF' | sudo tee "$nix_conf" > /dev/null
# Nix Configuration - Optimized for macOS
# Generated by dotfiles system-optimization.sh

# Build optimization
max-jobs = auto
cores = 0
parallel-shell-jobs = 4

# Binary caches
substituters = https://cache.nixos.org/ https://nix-community.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

# Store optimization
auto-optimise-store = true
min-free = 1073741824    # 1GB
max-free = 5368709120    # 5GB

# Build features
system-features = nixos-test benchmark big-parallel kvm

# Experimental features
experimental-features = nix-command flakes

# Keep outputs and derivations for development
keep-outputs = true
keep-derivations = true

# Sandbox builds (security)
sandbox = true
restrict-eval = true

# Logging
log-lines = 50
show-trace = true
EOF

    log_success "Optimized nix.conf configuration"
    
    # Restart nix-daemon to apply changes
    log_info "Restarting nix-daemon..."
    sudo launchctl unload /Library/LaunchDaemons/org.nixos.nix-daemon.plist 2>/dev/null || true
    sudo launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist
    log_success "Nix daemon restarted"
}

# Create automated maintenance launchd job
create_maintenance_schedule() {
    log_info "=== Setting up automated maintenance ==="
    
    local plist_file="$HOME/Library/LaunchAgents/com.dotfiles.maintenance.plist"
    
    # Create LaunchAgent for weekly maintenance
    cat << EOF > "$plist_file"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.dotfiles.maintenance</string>
    
    <key>ProgramArguments</key>
    <array>
        <string>$DOTFILES_DIR/scripts/nix-maintenance.sh</string>
        <string>maintenance</string>
    </array>
    
    <key>StartCalendarInterval</key>
    <dict>
        <key>Weekday</key>
        <integer>0</integer>
        <key>Hour</key>
        <integer>3</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    
    <key>StandardOutPath</key>
    <string>$HOME/Library/Logs/dotfiles-maintenance.log</string>
    
    <key>StandardErrorPath</key>
    <string>$HOME/Library/Logs/dotfiles-maintenance-error.log</string>
    
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
EOF

    # Load the launch agent
    launchctl unload "$plist_file" 2>/dev/null || true
    launchctl load "$plist_file"
    
    log_success "Automated weekly maintenance scheduled"
    log_info "Logs will be saved to: $HOME/Library/Logs/dotfiles-maintenance.log"
}

# Create system performance monitoring
setup_performance_monitoring() {
    log_info "=== Setting up performance monitoring ==="
    
    local monitor_script="$DOTFILES_DIR/scripts/performance-monitor.sh"
    
    cat << 'EOF' > "$monitor_script"
#!/bin/bash

# Performance Monitoring Script
set -euo pipefail

METRICS_DIR="$HOME/.dotfiles/metrics"
mkdir -p "$METRICS_DIR"

# Generate timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# System metrics
{
    echo "=== System Performance Report - $(date) ==="
    echo ""
    
    echo "## Memory Usage"
    vm_stat | head -10
    echo ""
    
    echo "## Disk Usage"
    df -h | head -5
    echo ""
    
    echo "## Nix Store Size"
    if command -v nix >/dev/null 2>&1; then
        nix store optimise --dry-run 2>/dev/null | tail -3 || echo "Nix store analysis unavailable"
    fi
    echo ""
    
    echo "## Top Processes"
    ps aux | head -10
    echo ""
    
    echo "## Load Average"
    uptime
    echo ""
    
} > "$METRICS_DIR/performance-$TIMESTAMP.log"

# Keep only last 30 days of metrics
find "$METRICS_DIR" -name "performance-*.log" -mtime +30 -delete 2>/dev/null || true

echo "Performance metrics saved to: $METRICS_DIR/performance-$TIMESTAMP.log"
EOF

    chmod +x "$monitor_script"
    log_success "Performance monitoring script created"
}

# Create automated security updates
setup_security_automation() {
    log_info "=== Setting up security automation ==="
    
    local security_script="$DOTFILES_DIR/scripts/security-updater.sh"
    
    cat << 'EOF' > "$security_script"
#!/bin/bash

# Automated Security Updates Script
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_FILE="$HOME/Library/Logs/dotfiles-security-updates.log"

log_with_timestamp() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Update flake.lock
update_flake_lock() {
    log_with_timestamp "Updating flake.lock..."
    cd "$DOTFILES_DIR/nix"
    
    if nix flake update; then
        log_with_timestamp "Successfully updated flake.lock"
        
        # Check if there are any changes
        if git diff --quiet flake.lock; then
            log_with_timestamp "No updates available"
        else
            log_with_timestamp "Changes detected in flake.lock"
            
            # Commit changes
            git add flake.lock
            git commit -m "chore: automated security update of flake.lock

🤖 Automated security update
$(date '+%Y-%m-%d %H:%M:%S')

Co-Authored-By: Security Automation <security@dotfiles.local>"
            
            log_with_timestamp "Committed flake.lock updates"
        fi
    else
        log_with_timestamp "ERROR: Failed to update flake.lock"
        return 1
    fi
}

# Run security checks
run_security_checks() {
    log_with_timestamp "Running security analysis..."
    
    if "$DOTFILES_DIR/scripts/enhanced-dependency-check.sh" security > /tmp/security-check.log 2>&1; then
        log_with_timestamp "Security check completed successfully"
    else
        log_with_timestamp "WARNING: Security check found issues - see /tmp/security-check.log"
    fi
}

# Main execution
main() {
    log_with_timestamp "=== Starting automated security update ==="
    
    update_flake_lock
    run_security_checks
    
    log_with_timestamp "=== Security update completed ==="
}

main "$@"
EOF

    chmod +x "$security_script"
    log_success "Security automation script created"
    
    # Create weekly security update schedule
    local security_plist="$HOME/Library/LaunchAgents/com.dotfiles.security-updates.plist"
    
    cat << EOF > "$security_plist"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.dotfiles.security-updates</string>
    
    <key>ProgramArguments</key>
    <array>
        <string>$DOTFILES_DIR/scripts/security-updater.sh</string>
    </array>
    
    <key>StartCalendarInterval</key>
    <dict>
        <key>Weekday</key>
        <integer>2</integer>
        <key>Hour</key>
        <integer>9</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    
    <key>StandardOutPath</key>
    <string>$HOME/Library/Logs/dotfiles-security-updates.log</string>
    
    <key>StandardErrorPath</key>
    <string>$HOME/Library/Logs/dotfiles-security-updates-error.log</string>
</dict>
</plist>
EOF

    launchctl unload "$security_plist" 2>/dev/null || true
    launchctl load "$security_plist"
    
    log_success "Weekly security updates scheduled (Tuesdays at 9 AM)"
}

# Create intelligent package analyzer
create_package_analyzer() {
    log_info "=== Creating intelligent package analyzer ==="
    
    local analyzer_script="$DOTFILES_DIR/scripts/package-intelligence.sh"
    
    cat << 'EOF' > "$analyzer_script"
#!/bin/bash

# Intelligent Package Analysis and Recommendations
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Analyze package usage patterns
analyze_usage_patterns() {
    log_info "=== Package Usage Pattern Analysis ==="
    
    local usage_file="$HOME/.dotfiles/package-usage.log"
    mkdir -p "$(dirname "$usage_file")"
    
    # Track command usage
    if [[ -f "$HOME/.zsh_history" ]]; then
        # Extract most used commands
        log_info "Most frequently used commands:"
        cat "$HOME/.zsh_history" | \
            sed 's/^: [0-9]*:[0-9]*;//' | \
            awk '{print $1}' | \
            sort | uniq -c | sort -nr | head -20 | \
            while read count cmd; do
                printf "  %3d: %s\n" "$count" "$cmd"
            done
    fi
    
    echo ""
    
    # Suggest package optimizations
    log_info "Package optimization suggestions:"
    
    # Check for unused packages
    local darwin_packages
    darwin_packages=$(nix eval --json ".#darwinConfigurations.yuki.config.environment.systemPackages" --file "$DOTFILES_DIR/nix/flake.nix" 2>/dev/null | jq -r '.[]' | sort | uniq)
    
    echo "📦 Currently managed packages: $(echo "$darwin_packages" | wc -l | tr -d ' ')"
    
    # Suggest missing common tools
    local common_tools=(
        "htop" "btop" "neofetch" "tree" "jq" "ripgrep" "fd" "bat" "eza"
        "zoxide" "starship" "tmux" "git" "gh" "curl" "wget" "vim" "neovim"
    )
    
    log_info "Checking for missing common development tools:"
    for tool in "${common_tools[@]}"; do
        if ! echo "$darwin_packages" | grep -q "^$tool$"; then
            if command -v "$tool" >/dev/null 2>&1; then
                log_success "✓ $tool (available but not in nix config)"
            else
                log_warning "⚠ $tool (missing - consider adding to nix)"
            fi
        else
            log_success "✓ $tool (managed by nix)"
        fi
    done
}

# Recommend system improvements
recommend_improvements() {
    log_info "=== System Improvement Recommendations ==="
    
    # Check system performance
    local load_avg
    load_avg=$(uptime | awk -F'load average:' '{print $2}' | awk '{print $1}' | tr -d ',')
    
    if (( $(echo "$load_avg > 2.0" | bc -l) )); then
        log_warning "High system load detected ($load_avg) - consider:"
        echo "  • Reducing parallel build jobs in nix"
        echo "  • Adding more swap space"
        echo "  • Investigating background processes"
    else
        log_success "System load is healthy ($load_avg)"
    fi
    
    # Check disk space
    local disk_usage
    disk_usage=$(df / | tail -1 | awk '{print $5}' | tr -d '%')
    
    if (( disk_usage > 85 )); then
        log_warning "Disk usage high (${disk_usage}%) - consider:"
        echo "  • Running 'nix store gc --older-than 30d'"
        echo "  • Running 'nix store optimise'"
        echo "  • Cleaning up old backups"
    else
        log_success "Disk usage is healthy (${disk_usage}%)"
    fi
    
    # Check nix store size
    local store_size
    if command -v nix >/dev/null 2>&1; then
        store_size=$(nix path-info --closure-size --human-readable nixpkgs#hello 2>/dev/null | head -1 || echo "Unknown")
        log_info "Nix store health: $store_size typical package closure"
    fi
}

# Generate optimization report
generate_report() {
    local report_file="$HOME/.dotfiles/optimization-report-$(date +%Y%m%d_%H%M%S).md"
    
    {
        echo "# System Optimization Report"
        echo "Generated: $(date)"
        echo ""
        
        echo "## System Status"
        echo "- Load Average: $(uptime | awk -F'load average:' '{print $2}')"
        echo "- Disk Usage: $(df -h / | tail -1 | awk '{print $5}')"
        echo "- Memory: $(vm_stat | grep 'Pages free' | awk '{print $3 * 4096 / 1024 / 1024 " MB free"}')"
        echo ""
        
        echo "## Nix Configuration"
        if [[ -f /etc/nix/nix.conf ]]; then
            echo "- Nix configuration: Optimized"
            echo "- Build parallelism: $(grep 'max-jobs' /etc/nix/nix.conf || echo 'Default')"
        else
            echo "- Nix configuration: Default (consider optimization)"
        fi
        echo ""
        
        echo "## Automation Status"
        if launchctl list | grep -q "com.dotfiles.maintenance"; then
            echo "- ✅ Automated maintenance: Enabled"
        else
            echo "- ❌ Automated maintenance: Disabled"
        fi
        
        if launchctl list | grep -q "com.dotfiles.security-updates"; then
            echo "- ✅ Security updates: Enabled"
        else
            echo "- ❌ Security updates: Disabled"
        fi
        
    } > "$report_file"
    
    log_success "Optimization report saved: $report_file"
}

# Main execution
main() {
    case "${1:-analyze}" in
        "analyze")
            analyze_usage_patterns
            echo ""
            recommend_improvements
            echo ""
            generate_report
            ;;
        "usage")
            analyze_usage_patterns
            ;;
        "recommendations")
            recommend_improvements
            ;;
        "report")
            generate_report
            ;;
        *)
            echo "Usage: $0 {analyze|usage|recommendations|report}"
            echo ""
            echo "Commands:"
            echo "  analyze         - Full analysis and report generation"
            echo "  usage          - Analyze package usage patterns"
            echo "  recommendations - System improvement recommendations"
            echo "  report         - Generate optimization report"
            exit 1
            ;;
    esac
}

main "$@"
EOF

    chmod +x "$analyzer_script"
    log_success "Intelligent package analyzer created"
}

# Main orchestration function
main() {
    case "${1:-all}" in
        "nix")
            optimize_nix_builds
            ;;
        "maintenance")
            create_maintenance_schedule
            ;;
        "monitoring")
            setup_performance_monitoring
            ;;
        "security")
            setup_security_automation
            ;;
        "intelligence")
            create_package_analyzer
            ;;
        "all")
            log_info "=== Complete System Optimization ==="
            echo ""
            
            optimize_nix_builds
            echo ""
            create_maintenance_schedule
            echo ""
            setup_performance_monitoring
            echo ""
            setup_security_automation
            echo ""
            create_package_analyzer
            echo ""
            
            log_success "=== All optimizations applied ==="
            echo ""
            echo "🎯 Your system is now running with maximum efficiency:"
            echo "  • Nix builds optimized with binary cache and parallel processing"
            echo "  • Weekly automated maintenance scheduled"
            echo "  • Performance monitoring enabled"
            echo "  • Security updates automated"
            echo "  • Intelligent package analysis available"
            echo ""
            echo "Run these commands to utilize new features:"
            echo "  scripts/performance-monitor.sh"
            echo "  scripts/package-intelligence.sh analyze"
            echo "  scripts/security-updater.sh"
            ;;
        *)
            echo "Usage: $0 {nix|maintenance|monitoring|security|intelligence|all}"
            echo ""
            echo "Optimization modules:"
            echo "  nix          - Optimize nix build configuration"
            echo "  maintenance  - Set up automated maintenance"
            echo "  monitoring   - Enable performance monitoring"
            echo "  security     - Configure security automation"
            echo "  intelligence - Create package intelligence system"
            echo "  all          - Apply all optimizations"
            exit 1
            ;;
    esac
}

main "$@"