# LSP Performance Optimization Configuration
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.dotfiles.development.lsp;
in
{
  config = mkIf (cfg.enable && cfg.performanceOptimization) {
    # System-level optimizations for LSP performance
    home-manager.users.yuki.home.file.".config/lsp/performance.conf" = {
      text = ''
        # LSP Performance Configuration
        # Generated by Nix configuration

        # Memory settings
        memory_limit=${cfg.memoryLimit}
        garbage_collection_threshold=0.8

        # CPU settings
        max_cpu_percent=50
        thread_pool_size=4

        # IO settings
        file_watcher_debounce=300
        max_file_watches=10000

        # Cache settings
        cache_enabled=true
        cache_size_mb=256
        cache_ttl_seconds=3600

        # Logging
        log_level=${cfg.logLevel}
        log_max_size_mb=50
        log_rotation_count=5

        # Network settings
        timeout_ms=5000
        max_concurrent_requests=10

        # Language-specific optimizations
        typescript_max_project_size=100000
        rust_check_on_save=true
        python_max_line_length=88
        go_use_language_server=true
      '';
    };

    # Performance monitoring configuration
    home-manager.users.yuki.home.file.".config/lsp/monitoring.json" = {
      text = builtins.toJSON {
        monitoring = {
          enabled = true;
          metrics = {
            memory_usage = true;
            cpu_usage = true;
            response_time = true;
            error_rate = true;
          };
          alerts = {
            high_memory_threshold = "500MB";
            high_cpu_threshold = "70%";
            slow_response_threshold = "2000ms";
            error_rate_threshold = "5%";
          };
        };
        reporting = {
          interval_seconds = 300;
          retention_days = 7;
          export_format = "json";
        };
      };
    };

    # LSP resource limits (using systemd user services on Linux)
    systemd.user.services = mkIf pkgs.stdenv.isLinux (listToAttrs (
      mapAttrsToList (name: server: {
        name = "lsp-${name}";
        value = {
          Unit = {
            Description = "LSP Server for ${name}";
            After = [ "graphical-session.target" ];
          };
          
          Service = {
            Type = "notify";
            ExecStart = "${server.package}/bin/${server.command}";
            Restart = "on-failure";
            RestartSec = 5;
            
            # Resource limits
            MemoryLimit = cfg.memoryLimit;
            CPUQuota = "50%";
            
            # Security
            NoNewPrivileges = true;
            ProtectSystem = "strict";
            ProtectHome = "read-only";
            PrivateTmp = true;
            
            # Environment
            Environment = [
              "LOG_LEVEL=${cfg.logLevel}"
              "PERFORMANCE_MODE=true"
            ];
          };
          
          Install = {
            WantedBy = [ "default.target" ];
          };
        };
      }) (filterAttrs (name: server: 
        elem name cfg.enabledLanguages
      ) lspServers)
    ));
  };
}