# Tokyo Night風カラー
color=foreground=c0caf5,foreground_text=1a1b26,background=1a1b26,background_text=c0caf5,curtain=1a1b26,success=9ece6a,error=f7768e

# タイムライン
timeline_style=bar
timeline_size=4
timeline_size_max=40
timeline_persistency=
timeline_border=1

# コントロール
controls=menu,gap,subtitles,<has_many_audio>audio,<has_many_video>video,<has_many_edition>editions,<stream>stream-quality,gap,space,speed,space,shuffle,loop-playlist,loop-file,gap,prev,items,next,gap,fullscreen
controls_persistency=

# トップバー
top_bar=always
top_bar_title=${media-title}
top_bar_persistency=

# ウィンドウ
window_border_size=0

# UI
opacity=timeline=0.9,position=0.9,chapters=0.3,slider=0.9,slider_gauge=0.3,speed=0.6,menu=1,submenu=1,border=1,title=0.9,tooltip=0.9,thumbnail=1,curtain=0.5,idle_indicator=0.8,audio_indicator=0.5,buffering_indicator=0.8,playlist_position=0.8
