# Server-side mods for the Fabric servers. Every one of these runs without anything on the
# client, so the servers stay open to a plain launcher. Lithium, FerriteCore, Krypton and
# Moonrise are the performance set that puts Fabric on par with Paper; Moonrise is Paper's own
# chunk system published as a mod.
#
# The list is regenerated by scripts/update-custom-packages.sh: the `# modrinth:` line above each
# entry names the project, and a game version is only adopted once every project here has a
# release for it. Hashes are the sha512 Modrinth publishes, so nothing is downloaded to pin them.
{ fetchurl }:
[
  # modrinth:P7dR8mSH fabric-api
  (fetchurl {
    name = "fabric-api-0.162.0+26.3.jar";
    url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/v2j28coa/fabric-api-0.162.0%2B26.3.jar";
    hash = "sha512-WrcJCJUvHSNG0WsSLKMTJ/QFXbWcJ5obw8PFgc41m7VBy6FXMPVbBye+fHxN68SkQSoYPCKODU3qgcc097QSzg==";
  })
  # modrinth:gvQqBUqZ lithium
  (fetchurl {
    name = "lithium-fabric-0.26.2+mc26.3.jar";
    url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/xS0Q8LSi/lithium-fabric-0.26.2%2Bmc26.3.jar";
    hash = "sha512-TX/uZhMu7ccf6rk5C5LJXXBY7b2tD+z6wdg2opULl6fKRjr77eYcfvNhzmXh+Sernond5b8uDgzkhq+1xdvuQA==";
  })
  # modrinth:uXXizFIs ferrite-core
  (fetchurl {
    name = "ferritecore-9.0.0-fabric.jar";
    url = "https://cdn.modrinth.com/data/uXXizFIs/versions/d5ddUdiB/ferritecore-9.0.0-fabric.jar";
    hash = "sha512-2B+pfhF4TBnUL4nC9DODHQB2A91xk87kX6F35KapxSs4SxmFhuBKD39jzZlv7XEzIleL3pqNtX4RiIVK5cvlhA==";
  })
  # modrinth:fQEb0iXm krypton optional
  (fetchurl {
    name = "krypton-0.3.2.jar";
    url = "https://cdn.modrinth.com/data/fQEb0iXm/versions/UugdIYJw/krypton-0.3.2.jar";
    hash = "sha512-0dV+vUE5W3WwHxMM2VA+uNIIISQko5n/nzZ/UL6PvBxkckQrM8aG53fDFI9qYJUg6PtzLHVRV8NYyyB/1NESOg==";
  })
  # modrinth:KOHu7RCS moonrise-opt optional
  (fetchurl {
    name = "Moonrise-Fabric-1.2.0+61c1328.jar";
    url = "https://cdn.modrinth.com/data/KOHu7RCS/versions/5WWnR77M/Moonrise-Fabric-1.2.0%2B61c1328.jar";
    hash = "sha512-pdO/MOsrW19PPSRJcEwUMUQs21tN4vUnrWX8lxFFs3l43W3kSWJRKhk4B94AXP56CBLExJrttjf6lfgTF7ZXdg==";
  })
  # modrinth:bWrNNfkb floodgate optional
  (fetchurl {
    name = "Floodgate-Fabric-2.2.7-b69.jar";
    url = "https://cdn.modrinth.com/data/bWrNNfkb/versions/m9eO07Zi/Floodgate-Fabric-2.2.7-b69.jar";
    hash = "sha512-kYX8lsDzAe4IZ9gwZcIQJ3BirT0VNunUIxJj+jLtMiPQCCaMSN6eAPDpoiQKLEXEOJNNAe+kCxtSOw0HLrMi1Q==";
  })
]
