# Server-side mods for the Fabric servers. Every one of these runs without anything on the
# client, so the servers stay open to a plain launcher. Lithium, FerriteCore, Krypton and
# Moonrise are the performance set that puts Fabric on par with Paper; Moonrise is Paper's own
# chunk system published as a mod.
#
# The list is regenerated by scripts/update-custom-packages.sh: the `# modrinth:` line above each
# entry names the project, and a game version is only adopted once every project here has a
# release for it. Hashes are the sha512 Modrinth publishes, so nothing is downloaded to pin them.
{ fetchurl }:
[
  # modrinth:P7dR8mSH fabric-api
  (fetchurl {
    name = "fabric-api-0.161.0+26.3.jar";
    url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/bNnaTiuM/fabric-api-0.161.0%2B26.3.jar";
    hash = "sha512-7Wslhtb94R/ehHL1pSfFHpm2cCbkb5TUv9hefijOXuKZFz7hatV2zrUfOfmNMKgRCGpt6xqGpSSFnMFuEtoQnQ==";
  })
  # modrinth:gvQqBUqZ lithium
  (fetchurl {
    name = "lithium-fabric-0.26.1+mc26.3.jar";
    url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/WXHRsMRl/lithium-fabric-0.26.1%2Bmc26.3.jar";
    hash = "sha512-rLubA3ogPwBeA6IL8dmGYBk4Srta0nZkgIoSuRljmiUB7LUvjw130n4UCZNbDb27cOAaxGZIDArkIe5AP2ScWQ==";
  })
  # modrinth:uXXizFIs ferrite-core
  (fetchurl {
    name = "ferritecore-9.0.0-fabric.jar";
    url = "https://cdn.modrinth.com/data/uXXizFIs/versions/d5ddUdiB/ferritecore-9.0.0-fabric.jar";
    hash = "sha512-2B+pfhF4TBnUL4nC9DODHQB2A91xk87kX6F35KapxSs4SxmFhuBKD39jzZlv7XEzIleL3pqNtX4RiIVK5cvlhA==";
  })
  # modrinth:fQEb0iXm krypton optional
  # (no release for 26.3 yet)
  # modrinth:KOHu7RCS moonrise-opt optional
  # (no release for 26.3 yet)
  # modrinth:bWrNNfkb floodgate optional
  (fetchurl {
    name = "Floodgate-Fabric-2.2.7-b69.jar";
    url = "https://cdn.modrinth.com/data/bWrNNfkb/versions/m9eO07Zi/Floodgate-Fabric-2.2.7-b69.jar";
    hash = "sha512-kYX8lsDzAe4IZ9gwZcIQJ3BirT0VNunUIxJj+jLtMiPQCCaMSN6eAPDpoiQKLEXEOJNNAe+kCxtSOw0HLrMi1Q==";
  })
]
