#!/usr/bin/env bun
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import * as path from "node:path";

const lazy2nixDir = import.meta.dir;
const repoRoot = path.resolve(lazy2nixDir, "../../../..");
const lockPath = path.join(repoRoot, "configs/editors/nvim/lazy-lock.json");

interface DumpedPlugin {
  name: string;
  url?: string;
  virtual: boolean;
  version?: string | boolean;
  branch?: string;
  commit?: string;
  has_build: boolean;
}

interface PinnedPlugin {
  owner: string;
  repo: string;
  rev: string;
  hash: string;
}

function run(command: string[], env?: Record<string, string>): string {
  const process = Bun.spawnSync(command, {
    cwd: repoRoot,
    env: { ...Bun.env, ...env },
    stderr: "pipe",
  });
  if (process.exitCode !== 0) {
    throw new Error(`${command.join(" ")} failed:\n${process.stderr.toString()}`);
  }
  return process.stdout.toString();
}

async function readJson<T>(file: string): Promise<T> {
  return (await Bun.file(file).json()) as T;
}

function dumpPlugins(): DumpedPlugin[] {
  const directory = mkdtempSync(path.join(tmpdir(), "lazy2nix-"));
  const dumpPath = path.join(directory, "plugins.json");
  try {
    run(["nvim", "--headless", `+lua dofile('${path.join(lazy2nixDir, "dump.lua")}')`, "+qa"], {
      LAZY2NIX_DUMP: dumpPath,
    });
    return JSON.parse(run(["cat", dumpPath]));
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

function nixpkgsPluginIndex(): Map<string, string> {
  const expression =
    "vp: builtins.listToAttrs (builtins.concatMap (n: let r = builtins.tryEval (let p = vp.${n}; in if builtins.isAttrs p && p ? pname && p ? outPath then p.pname else null); in if r.success && builtins.isString r.value then [ { name = n; value = r.value; } ] else [ ]) (builtins.attrNames vp))";
  const attributes = JSON.parse(
    run([
      "nix",
      "eval",
      "--json",
      "--inputs-from",
      path.join(repoRoot, "nix"),
      "nixpkgs#vimPlugins",
      "--apply",
      expression,
    ]),
  ) as Record<string, string>;
  const index = new Map<string, string>();
  for (const [attribute, pname] of Object.entries(attributes).sort()) {
    const key = pname.toLowerCase();
    if (!index.has(key) || attribute.toLowerCase() === pname.toLowerCase().replaceAll(".", "-")) {
      index.set(key, attribute);
    }
  }
  return index;
}

function prefetchGitHub(owner: string, repo: string, rev: string): string {
  const result = run(["nix", "flake", "prefetch", "--json", `github:${owner}/${repo}/${rev}`]);
  return JSON.parse(result).hash as string;
}

const config = await readJson<{ exclude: string[]; overrides: Record<string, string> }>(
  path.join(lazy2nixDir, "config.json"),
);
const lock = await readJson<Record<string, { commit: string }>>(lockPath);
const previous = await readJson<Record<string, PinnedPlugin>>(
  path.join(lazy2nixDir, "pinned-plugins.json"),
);
const excluded = new Set(config.exclude);

console.log("Resolving lazy.nvim plugins...");
const plugins = dumpPlugins();
console.log(`  ${plugins.length} plugins`);
console.log("Indexing nixpkgs vimPlugins...");
const index = nixpkgsPluginIndex();
const fromNixpkgs: Record<string, string> = {};
const pinned: Record<string, PinnedPlugin> = {};

for (const plugin of plugins) {
  if (plugin.virtual || !plugin.url || plugin.url.includes("github.com/gapul/") || excluded.has(plugin.name)) {
    continue;
  }
  if (plugin.has_build) {
    console.warn(`warning: ${plugin.name} has a build step; add it to config.json exclude if required`);
  }
  const attribute = config.overrides[plugin.name] ?? index.get(plugin.name.toLowerCase());
  if (attribute) {
    fromNixpkgs[plugin.name] = attribute;
    continue;
  }
  const match = plugin.url.match(/github\.com\/([^/]+)\/(.+?)(?:\.git)?$/);
  const rev = lock[plugin.name]?.commit ?? previous[plugin.name]?.rev;
  if (!match || !rev) {
    console.warn(`warning: ${plugin.name} cannot be pinned; leaving it to lazy.nvim`);
    continue;
  }
  const [, owner, repo] = match;
  const old = previous[plugin.name];
  const hash = old?.rev === rev ? old.hash : prefetchGitHub(owner, repo, rev);
  pinned[plugin.name] = { owner, repo, rev, hash };
}

const sortedNixpkgs = Object.fromEntries(
  Object.entries(fromNixpkgs).sort(([left], [right]) => left.localeCompare(right)),
);
const sortedPinned = Object.fromEntries(
  Object.entries(pinned).sort(([left], [right]) => left.localeCompare(right)),
);
const nixLines = [
  "# Generated by lazy2nix. Run `nix run ./nix#lazy2nix` to refresh.",
  "{",
  ...Object.entries(sortedNixpkgs).map(([name, attribute]) => `  "${name}" = "${attribute}";`),
  "}",
  "",
];
await Bun.write(path.join(lazy2nixDir, "nixpkgs-plugins.nix"), nixLines.join("\n"));
await Bun.write(
  path.join(lazy2nixDir, "pinned-plugins.json"),
  `${JSON.stringify(sortedPinned, null, 2)}\n`,
);
console.log(
  `Wrote ${Object.keys(sortedNixpkgs).length} nixpkgs plugins and ${Object.keys(sortedPinned).length} pinned plugins.`,
);
